italanta/elewa

.github/pull_request_template.md
Added pull request template so as to auto-populate the issue/pull-request description field and provide a skeleton framework that one can fill out.  The template provides a baseline standard of making a pull request in this repository.
=> chore: :wrench: Added a pull request template

CONTRIBUTING.md
Added contributing guidelines documentation.
=> :memo: Add contributing guidelines

libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
This PR fixes an issue with PR #50.
Bug Fix
=> :bug: (fix) Fixes the issue of the location block not being displayed

docs/styleguide.md, docs/tsguide.md
Added TypeScript guide and style guide in docs folder. Resolves(#41)
The info added in docs includes:
- TypeScript style guide
- Info about order of imports for Angular application
- Info about the source code folder  structure
=> [WIP]🚧 #41 📝 docs: Add style guide documentation 

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json
Fixes #77 
Added translations for bots on the en.json and fr.json files as as requested in the issue.
=> {refactor} Bot translations

libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.html, libs/features/convs-mgr/home/src/lib/components/story-list/story-list.component.html, libs/features/convs-mgr/home/src/lib/components/story-list/story-list.component.scss, libs/features/convs-mgr/home/src/lib/modals/create-bot-modal/create-bot-modal.component.ts
Some Icons were missing i.e the search and bot menu they were not being rendered correctly. I added material icons to generate the icons and be displayed them correctly.
ref #115 
This change fixes issue ref#115
=> 🐛 🎨 Icons are not properly rendering-made change to render properly

apps/conv-learning-manager/src/app/app.module.ts, apps/conv-learning-manager/src/main.ts
Just a small hotfix to resolve environments issue.
=> :fire: :wrench: renamed the environment file

angular.json, apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.html, libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.ts, libs/features/convs-mgr/home/src/lib/convs-mgr-home.module.ts, libs/features/convs-mgr/home/src/lib/modals/create-bot-modal/create-bot-modal.component.html, libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.html, libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.scss, libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.spec.ts, libs/features/convs-mgr/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.ts, libs/features/convs-mgr/home/src/lib/pages/home/home.page.html, libs/features/convs-mgr/home/src/lib/services/new-story.service.ts, tsconfig.base.json
Deletes a bot as per the specification. Ref(#104). Everything works as expected
Fixes #104 
Fixes #102 -> Builds from PR #105
Features:
https://user-images.githubusercontent.com/20738858/198207973-4294b5d3-79c5-45ac-b028-5dfd876d9f2d.mp4
=> :sparkles: Delete Bot Ref #104

libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
I implemented this solution by filtering the blocks on the story editor frame. Then I set block deleted to true
Fixes #14,
=> 🎨 (feat) delete block

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/elements/theming/_variables.scss, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.scss, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/anchor-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/audio-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/document-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/email-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/image-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/list-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/location-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/message-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/name-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/phonenumber-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/questions-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/reply-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/sticker-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/video-block.jsplumb.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
Add icons and block titles, move  anchors to left side of the blocks and add translations for the titles
Fixes #143
=> 🧱  🔨 Block layout and Functionality

libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.html
=> :art: fixed story list width

libs/features/convs-mgr/stories/blocks/library/text-message-block/src/lib/components/message-block/message-block.component.html, libs/features/convs-mgr/stories/blocks/library/text-message-block/src/lib/components/message-block/message-block.component.scss, libs/features/convs-mgr/stories/blocks/library/text-message-block/src/lib/components/message-block/message-block.component.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
In this issue I redesigned the features  in message block component as per the requirements.
Fixes # 145
=> 🧱 🔨Message block

libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts, libs/functions/bot-engine/main/src/lib/model/active-channel.service.ts, libs/functions/bot-engine/main/src/lib/services/bot-engine-main.service.ts, libs/functions/bot-engine/main/src/lib/services/media/process-media-service.ts, libs/functions/bot-engine/whatsapp/src/lib/models/whatsapp-active-channel.model.ts, libs/model/convs-mgr/conversations/messages/src/lib/message.interface.ts, libs/state/file/store/src/lib/model/file-upload.interface.ts
This PR implements receiving media files from the end user, retrieving them from the whatsapp api and saving them to firebase storage.
=> 🔀 🤖 📷 ✨ Implement handling of media files - #3

libs/features/app/auth/login/src/lib/components/login/login.component.html, libs/features/app/auth/login/src/lib/components/login/login.component.scss, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.html, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.scss
This PR follows the design requirements for the login page. It is more responsive and the user is engaged during the process
Fixes issue https://github.com/italanta/elewa/issues/129 
UI and responsiveness fix.
=> 🎨🔥 Login-UI

libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.html, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.scss, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts
=> Block listing

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.html, libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.scss, libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/audio-block.jsplumb.ts
Changed the User Interface to match the design specifications by changing the font awesome and styling the icon to match the specification
Fixes #152 
=> 🧱 🎤 Audio block - Output #176

libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.ts
#Description
Quickfix for list interface
=> 🐛 List block interface bug

libs/elements/layout/page-convl/src/lib/components/convl-navbar/navbar.component.html, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts, libs/elements/layout/page-convl/src/lib/components/convl-sidenav-container/nav-wrapper.component.html, libs/elements/layout/page/src/lib/components/sidemenu/sidemenu.component.scss
Collapsible side-nav
The  sidenav minimizes  to only shoe the nav icons. When the sidenav is fully active it show text and icons
ot (optional)
=> :art: collapsed side-nav

apps/conv-lm-backend/src/main.ts, libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts, libs/functions/bot-engine/main/src/lib/io/block-to-message-parser.class.ts, libs/functions/bot-engine/main/src/lib/services/bot-engine-main.service.ts, libs/functions/bot-engine/main/src/lib/services/data-services/blocks.service.ts, libs/functions/bot-engine/main/src/lib/services/data-services/connections.service.ts, libs/functions/bot-engine/main/src/lib/services/data-services/cursor.service.ts, libs/functions/bot-engine/main/src/lib/services/process-message/process-message.service.ts, libs/functions/bot-engine/main/src/lib/services/variable-injection/variable-injector.service.ts, libs/functions/bot-engine/whatsapp/src/lib/io/incoming-message-parser/whatsapp-api-incoming-message-parser.class.ts, libs/functions/bot-engine/whatsapp/src/lib/io/outgoing-message-parser/whatsapp-api-outgoing-message-parser.class.ts, libs/model/convs-mgr/conversations/messages/src/lib/message.interface.ts
Debugging the bot engine after new changes implementation
=> Fix Bugs crashing the bot engine

libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts
=> :wrench: fixed save problem

libs/functions/bot-engine/README.md, libs/functions/bot-engine/whatsapp/README.md
Add Documentation on how one can register on the meta developer and deploying the bot cloud function. This will assist testing and resolving backend issues.
=> 🔀 💡 Add Documentation on registering on meta developer and deploying the bot cloud function

apps/conv-learning-manager/src/styles.scss, libs/elements/theming/common.theme.scss, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.scss, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/message-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/text-message-block/src/lib/components/message-block/message-block.component.html, libs/features/convs-mgr/stories/blocks/library/text-message-block/src/lib/components/message-block/message-block.component.ts, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.html, libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.html, libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.scss, libs/features/convs-mgr/stories/editor/src/lib/convl-story-editor.module.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.html, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.scss, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
=> :construction: added zoom to frame and lower z index for connectors

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/video-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.html, libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.scss, libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.ts
This code captures the changes to the video output user interface
Fixes # 154
=> Video block output

.github/workflows/github-actions-run-tests.yml
Setup a github action to build and run tests. Uses `nx affected` to only run tests on the projects that have been affected by that pull request.
=> 🔀 🧪 Setup a GitHub action to run tests

libs/functions/bot-engine/whatsapp/src/lib/io/incoming-message-parser/whatsapp-api-incoming-message-parser.test.ts, libs/functions/bot-engine/whatsapp/src/lib/io/outgoing-message-parser/whatsapp-api-outgoing-message-parser.test.ts
This pr contains a sample unit test for parsing in the whatsapp sticker message. This test will act as a reference point for writing tests for other whatsapp message parsers.
=> 🔀 🧪 Create sample unit test for whatsapp message parsers

firebase.json
Add predeploy command to build for firebase hosting deploys
=> 🔀 📜  add predeploy command to build for firebase hosting deploys

libs/features/convs-mgr/stories/home/src/lib/components/story-list-item/story-list-item.component.html, libs/features/convs-mgr/stories/home/src/lib/components/story-list-item/story-list-item.component.scss, libs/features/convs-mgr/stories/home/src/lib/pages/stories-dashboard/stories-dashboard.component.html, libs/features/convs-mgr/stories/home/src/lib/pages/stories-dashboard/stories-dashboard.component.scss
styling bots
Some components on the active bots had lost their styling. 
=> :art: Styling buttons (open bot and create new button)

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.html, libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.ts, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.html
Fix add to channel button not working because of incorrect form control names
=> 🐛 Fix add to channel button not working

libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/audio-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/document-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/email-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/image-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/list-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/location-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/message-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/name-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/phonenumber-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/questions-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/reply-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/sticker-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/video-block.jsplumb.ts
Increase number of connections towards a block.
=> 🎨 Increase number of connections towards a block

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/multiple-input-message-block-form.model.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/multiple-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/.eslintrc.json, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/README.md, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/jest.config.ts, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/index.ts, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/lib/components/multiple-input-block/multiple-input-block.component.html, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/lib/components/multiple-input-block/multiple-input-block.component.scss, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/lib/components/multiple-input-block/multiple-input-block.component.spec.ts, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/lib/components/multiple-input-block/multiple-input-block.component.ts, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/lib/convs-mgr-multiple-input-message-block.module.ts, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/test-setup.ts, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/tsconfig.json, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/tsconfig.lib.json, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/tsconfig.spec.json, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-types.enum.ts, libs/model/convs-mgr/stories/blocks/messaging/src/index.ts, libs/model/convs-mgr/stories/blocks/messaging/src/lib/multiple-input-message-block.interface.ts
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).
Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.
* Hardware:
* Toolchain:
* SDK:
=> Multiple input block

libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/manage-channel-story-link.service.ts
Add counter to incement 'n' when publishing a story using firebase [transactions](https://firebase.google.com/docs/firestore/manage-data/transactions).
=> 🔀 🏇 Add counter to increment 'n' when publishing a story

libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.html, libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.scss, libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.ts, libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.html, libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.scss, libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.ts, libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/convs-mgr-question-block.module.ts, libs/model/convs-mgr/stories/blocks/messaging/src/lib/list-message-block.interface.ts
deleting inputs
A user can  be able to delete a option from a block that accepts multiple options. These includes question blocks and list blocks.
=> 🎨 🔢 A user can be able to delete options from blocks that accepts multiple options

angular.json, libs/features/convs-mgr/stories/blocks/library/fail-block/.eslintrc.json, libs/features/convs-mgr/stories/blocks/library/fail-block/README.md, libs/features/convs-mgr/stories/blocks/library/fail-block/jest.config.ts, libs/features/convs-mgr/stories/blocks/library/fail-block/src/index.ts, libs/features/convs-mgr/stories/blocks/library/fail-block/src/lib/components/fail-block/fail-block.component.html, libs/features/convs-mgr/stories/blocks/library/fail-block/src/lib/components/fail-block/fail-block.component.scss, libs/features/convs-mgr/stories/blocks/library/fail-block/src/lib/components/fail-block/fail-block.component.ts, libs/features/convs-mgr/stories/blocks/library/fail-block/src/lib/convs-mgr-fail-block.module.ts, libs/features/convs-mgr/stories/blocks/library/fail-block/src/lib/features-convs-mgr-stories-blocks-library-fail-block.module.ts, libs/features/convs-mgr/stories/blocks/library/fail-block/src/test-setup.ts, libs/features/convs-mgr/stories/blocks/library/fail-block/tsconfig.json, libs/features/convs-mgr/stories/blocks/library/fail-block/tsconfig.lib.json, libs/features/convs-mgr/stories/blocks/library/fail-block/tsconfig.spec.json, libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/fail-block-form.model.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/fail-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-types.enum.ts, libs/model/convs-mgr/stories/blocks/messaging/src/index.ts, libs/model/convs-mgr/stories/blocks/messaging/src/lib/fail-block.interface.ts, tsconfig.base.json
This pr contains the implementation of a simple fail block, with a message box.
=> 🔀 🎨 ❗ Create a fail block

angular.json, apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/blocks/library/image-input-block/README.md, libs/features/convs-mgr/stories/blocks/library/image-input-block/src/index.ts, libs/features/convs-mgr/stories/blocks/library/image-input-block/src/lib/components/image-input-block/image-input-block.component.html, libs/features/convs-mgr/stories/blocks/library/image-input-block/src/lib/components/image-input-block/image-input-block.component.scss, libs/features/convs-mgr/stories/blocks/library/image-input-block/src/lib/components/image-input-block/image-input-block.component.ts, libs/features/convs-mgr/stories/blocks/library/image-input-block/src/lib/convs-mgr-image-input-block.modules.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/image-input-block-form.model.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/image-input-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/model/convs-mgr/stories/blocks/messaging/src/index.ts, tsconfig.base.json
=> :art: IMAGE INPUT BLOCK

libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/audio-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/audio-input-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/document-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/email-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/fail-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/image-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/image-input-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/list-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/location-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/location-input-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/message-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/name-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/phonenumber-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/questions-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/reply-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/sticker-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/video-block.jsplumb.ts
Set unlimited number of block connections on jsplumb
=> 🔀 🎨 Set unlimited number of block connections on jsplumb

libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/components/end-anchor/end-anchor.component.ts, libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/convs-mgr-stories-blocks-library-anchor-block.module.ts, libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/providers/jsplumb-target-decorator.function.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/end-story-anchor-block-form.model.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/features/convs-mgr/stories/home/src/lib/modals/create-bot-modal/create-bot-modal.component.html, libs/features/convs-mgr/stories/home/src/lib/modals/create-bot-modal/create-bot-modal.component.scss, libs/features/convs-mgr/stories/home/src/lib/modals/create-bot-modal/create-bot-modal.component.ts, libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-types.enum.ts, libs/model/convs-mgr/stories/blocks/messaging/src/index.ts, libs/model/convs-mgr/stories/blocks/messaging/src/lib/end-story-anchor.interface.ts, libs/state/convs-mgr/stories/blocks/src/lib/stores/story-blocks.store.ts, libs/state/convs-mgr/story-editor/src/lib/providers/story-editor-state.service.ts
Implemented the end anchor block
=> :rocket: implemented the end anchor block

libs/features/convs-mgr/stories/blocks/library/webhook-block/src/lib/components/webhook-block/webhook-block.component.html
Added missing form control name to webhook block fields
=> Added missing form control name to webhook block fields

angular.json, apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/open-ended-question-block-form.model.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/open-ended-question-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/.eslintrc.json, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/README.md, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/jest.config.ts, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/index.ts, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/components/open-ended-question-block/open-ended-question-block.component.html, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/components/open-ended-question-block/open-ended-question-block.component.scss, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/components/open-ended-question-block/open-ended-question-block.component.ts, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/convs-mgr-open-ended-question-block.module.ts, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/features-convs-mgr-stories-blocks-library-open-ended-question-block.module.ts, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/test-setup.ts, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/tsconfig.json, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/tsconfig.lib.json, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/tsconfig.spec.json, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-types.enum.ts, libs/model/convs-mgr/stories/blocks/messaging/src/index.ts, libs/model/convs-mgr/stories/blocks/messaging/src/lib/open-ended-question-block.interface.ts, tsconfig.base.json
Open Ended Question Block.
Fixes https://github.com/italanta/elewa/issues/275
=> :art:Open question block

libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
fixes the duplicated jsPlumb connections when saving to firestore
Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).
Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.
* Hardware:
* Toolchain:
* SDK:
=> :wrench: fix con duplicates

libs/features/convs-mgr/stories/blocks/library/audio-input-block/src/lib/audio-input-message-block/audio-input-message-block.component.scss, libs/features/convs-mgr/stories/blocks/library/audio-message-block/src/lib/components/audio-block/audio-block.component.scss, libs/features/convs-mgr/stories/blocks/library/document-message-block/src/lib/components/document-block/document-block.component.scss, libs/features/convs-mgr/stories/blocks/library/email-message-block/src/lib/components/email-block/email-block.component.scss, libs/features/convs-mgr/stories/blocks/library/fail-block/src/lib/components/fail-block/fail-block.component.scss, libs/features/convs-mgr/stories/blocks/library/image-input-block/src/lib/components/image-input-block/image-input-block.component.scss, libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.scss, libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.html, libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.scss, libs/features/convs-mgr/stories/blocks/library/location-input-block/src/lib/location-input-block/location-input-block.component.scss, libs/features/convs-mgr/stories/blocks/library/location-message-block/src/lib/components/location-block/location-block.component.scss, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/list-block-form.model.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/block-injector.service.ts, libs/features/convs-mgr/stories/blocks/library/multiple-input-message-block/src/lib/components/multiple-input-block/multiple-input-block.component.scss, libs/features/convs-mgr/stories/blocks/library/name-message-block/src/lib/components/name-block/name-block.component.scss, libs/features/convs-mgr/stories/blocks/library/phone-message-block/src/lib/components/phone-block/phone-block.component.scss, libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.scss, libs/features/convs-mgr/stories/blocks/library/reply-message-block/src/lib/components/reply-block/reply-block.component.scss, libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.scss, libs/features/convs-mgr/stories/blocks/library/text-message-block/src/lib/components/message-block/message-block.component.scss, libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.scss, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
=> :rocket: worked on duplicate block

libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.ts
Remove character limit on whatsapp phone number id. In the whatsapp create channel form
=> 🎨 🔀  Remove character limit on whatsapp phone number id

libs/features/convs-mgr/stories/editor/src/lib/convl-story-editor.module.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/manage-jsPlumb-connections.function.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/story-editor-initialiser.service.ts, libs/features/convs-mgr/stories/editor/tsconfig.lib.json, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-connection.interface.ts, libs/state/convs-mgr/stories/block-connections/src/lib/services/block-connections.service.ts, libs/state/convs-mgr/story-editor/src/lib/providers/story-editor-state.service.ts
This code enables the user to delete the files from the editor frame and the firestore database
Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).
Fixes #276,  
A new feature 
* Hardware:
* Toolchain:
* SDK:
=> 🎨 Delete connections update

libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
Resolved conflicts for the delete-block-button
* Hardware:
* Toolchain:
* SDK:
=> Delete block button

libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
Fix block not being deleted after save
=> 🔀 🐛  Fix block not being deleted after save

libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/index.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/convs-mgr-edit-block-module.ts
=> :bug:  fix: image edit block import bug

angular.json, apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/video-input-block-form.model.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/video-input-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/video-input-block/.eslintrc.json, libs/features/convs-mgr/stories/blocks/library/video-input-block/README.md, libs/features/convs-mgr/stories/blocks/library/video-input-block/jest.config.ts, libs/features/convs-mgr/stories/blocks/library/video-input-block/src/index.ts, libs/features/convs-mgr/stories/blocks/library/video-input-block/src/lib/components/video-input-block/video-input-block.component.html, libs/features/convs-mgr/stories/blocks/library/video-input-block/src/lib/components/video-input-block/video-input-block.component.scss, libs/features/convs-mgr/stories/blocks/library/video-input-block/src/lib/components/video-input-block/video-input-block.component.ts, libs/features/convs-mgr/stories/blocks/library/video-input-block/src/lib/convs-mgr-video-input-block.module.ts, libs/features/convs-mgr/stories/blocks/library/video-input-block/src/test-setup.ts, libs/features/convs-mgr/stories/blocks/library/video-input-block/tsconfig.json, libs/features/convs-mgr/stories/blocks/library/video-input-block/tsconfig.lib.json, libs/features/convs-mgr/stories/blocks/library/video-input-block/tsconfig.spec.json, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-types.enum.ts, libs/model/convs-mgr/stories/blocks/messaging/src/index.ts, libs/model/convs-mgr/stories/blocks/messaging/src/lib/video-input-block.interface.ts, tsconfig.base.json
Video Input Block
Created a video input block that allows us to request a user to send a video (frontend)
* Hardware:
* Toolchain:
* SDK:
=> :art: video-input-block

apps/conv-learning-manager/src/styles.scss, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/manage-jsPlumb-connections.function.ts
The connections now appear behind the blocks. On a hover effect the color of the connector changes and adds an overlay delete button as shown in the screenshot.
Fixes #291
* Hardware:
* Toolchain:
* SDK:
=> 💄 Connector UI fix

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/app/auth/login/src/lib/components/login/login.component.html
Fix proceed button not working on login
=> 🎨 🐛 🔀 Fix proceed button not working on login

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/index.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/email-block-edit/email-block-edit.component.html, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/email-block-edit/email-block-edit.component.scss, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/email-block-edit/email-block-edit.component.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/name-block-edit/name-block-edit.component.html, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/name-block-edit/name-block-edit.component.scss, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/name-block-edit/name-block-edit.component.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/phone-block-edit/phone-block-edit.component.html, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/phone-block-edit/phone-block-edit.component.scss, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/phone-block-edit/phone-block-edit.component.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/convs-mgr-edit-block-module.ts, libs/features/convs-mgr/stories/blocks/library/email-message-block/src/lib/components/email-block/email-block.component.html, libs/features/convs-mgr/stories/blocks/library/email-message-block/src/lib/components/email-block/email-block.component.scss, libs/features/convs-mgr/stories/blocks/library/email-message-block/src/lib/components/email-block/email-block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/index.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/name-message-block/src/lib/components/name-block/name-block.component.html, libs/features/convs-mgr/stories/blocks/library/name-message-block/src/lib/components/name-block/name-block.component.scss, libs/features/convs-mgr/stories/blocks/library/name-message-block/src/lib/components/name-block/name-block.component.ts, libs/features/convs-mgr/stories/blocks/library/phone-message-block/src/lib/components/phone-block/phone-block.component.html, libs/features/convs-mgr/stories/blocks/library/phone-message-block/src/lib/components/phone-block/phone-block.component.scss, libs/features/convs-mgr/stories/blocks/library/phone-message-block/src/lib/components/phone-block/phone-block.component.ts, libs/features/convs-mgr/stories/editor/src/lib/model/portal-data.model.ts, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/block-portal.service.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/fetch-active-block-component.function.ts
Edit forms for Name, Email and Phone blocks.
=> :pencil2: :bricks: Name email and Phone edit forms

libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.html, libs/features/convs-mgr/stories/blocks/library/sticker-message-block/src/lib/components/sticker-block/sticker-block.component.ts
Removes the caption field on the sticker block. Quick Fix.
=> :adhesive_bandage: Quick-Fix: remove caption on sticker block

libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/components/video-block/video-block.component.html
Disable autoplay on uploaded videos
=> 🔀 🎨 🎥  Remove autoplay from uploaded videos

libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/keyword-jump-block-edit/keyword-jump-block-edit.component.html, libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.ts, libs/features/convs-mgr/stories/blocks/library/keyword-jump-block/src/lib/components/keyword-jump-block/keyword-jump-block.component.html
Fix connectors not showing on options
=> :bug: :art: fix connectors not showing on options

libs/util/ngfi/angular/src/lib/backend/backend.service.ts
Fix backend service circular dependency error
=> :bug: :scroll: fix backend service circular dependency

README.md, libs/state/convs-mgr/story-editor/src/lib/providers/story-editor-state.service.ts
Fix for save button not saving consistently and providing an error message incase save is not succesful.
=> 🔧  Save btn fix

libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.html, libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.scss, libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.ts, libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts, libs/state/file/store/src/lib/providers/file-storage.service.ts
Fixed asset upload service (to be reused for all blocks and bot)
=> :art: fixed file service upload

libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.html, libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.html, libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.scss, libs/features/convs-mgr/stories/blocks/library/image-message-block/src/lib/components/image-block/image-block.component.ts, libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts, libs/state/file/store/src/lib/providers/file-storage.service.ts
=> Options fix

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, apps/conv-learning-manager/src/styles.scss, libs/elements/layout/page-convl/src/lib/components/convl-page/convl-page.component.scss, libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.scss, libs/features/convs-mgr/stories/blocks/library/jump-story-block/src/lib/components/jump-block/jump-block.component.html, libs/features/convs-mgr/stories/blocks/library/jump-story-block/src/lib/components/jump-block/jump-block.component.scss, libs/features/convs-mgr/stories/blocks/library/jump-story-block/src/lib/components/jump-block/jump-block.component.ts, libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.html, libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.scss
Ui Update - Jump-block translations and dynamically responsive bots section.
=> UI quick fix

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts
=> :memo: update translations

libs/features/convs-mgr/stories/editor/src/lib/convl-story-editor.module.ts, libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.html, libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.scss, libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.ts, libs/model/convs-mgr/conversations/admin/system/src/index.ts
This PR is made in part to provide users with a guide when publishing a story in steps as this will simplify the process. This has been implemented using Angular Material Stepper.
Fixes #341
https://user-images.githubusercontent.com/56071589/224491565-061809c9-f7b4-435e-a0bc-1a0b42bb7fe9.mp4
=> ✨ 💄  Enhance the Publish Story Form UI

libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.ts
=> ✨feat: added type:whatsapp to the properties

apps/conv-learning-manager/src/assets/i18n/en.json, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss, libs/features/convs-mgr/stories/editor/src/lib/convl-story-editor.module.ts, libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.html, libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.ts
- Quick fix infinity scroll template parsing error. 
- Also sets the stepper as linear (for proper validation before the next step).
=> :bug: quick fix infinity scroll

libs/functions/bot-engine/main/src/lib/services/process-message/process-message.service.ts, libs/functions/bot-engine/main/src/lib/services/process-operation-block/process-operation-block.factory.ts
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/italanta-apps/issues).
Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.
* Hardware:
* Toolchain:
* SDK:
=> 🐛 Fix jumping back to previous story

libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts
Collect the latest user Info on render (while switching between users)
=> :bug: fix: get latest dashboard Info on render

libs/features/convs-mgr/conversations/chats/src/lib/components/chat-conversation/chat-conversation.component.html, libs/features/convs-mgr/conversations/chats/src/lib/pipes/filter.pipe.ts
fix the Filter by user's phone number
=> :bug: filter by phonenumber functionality

libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.html, libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts, libs/features/convs-mgr/conversations/chats/src/lib/modals/move-chat-modal/move-chat-modal.component.ts, libs/functions/bot-engine/main/src/lib/handlers/move-chat.handler.ts
Add functionality to unblock stuck users by a button. Currently a user has to be manually moved to the story they are in so that they can continue from there. And this means they will have to start from the beginning of current story.
Therefore this feature also acts as an enhancement since it will automatically send the last block sent to the end user by the bot.
=> 🔀 🎨 ❗ Add unblock user button

libs/features/convs-mgr/conversations/chats/src/lib/components/chat-conversation/chat-conversation.component.html, libs/features/convs-mgr/conversations/chats/src/lib/components/chat-conversation/chat-conversation.component.ts, libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.html, libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts
Fetch Chat details at the conversation level and then pass them to the header.
=> :sparkles: feat: Quick Fix Chat Details Header

libs/features/convs-mgr/conversations/messaging/src/lib/components/new-message/new-message.component.ts, libs/functions/bot-engine/main/src/lib/engine-bot-manager.handler.ts, libs/functions/bot-engine/main/src/lib/handlers/send-outgoing-message.handler.ts, libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts, libs/functions/bot-engine/whatsapp/src/lib/whatsapp-send-message.handler.ts, libs/model/convs-mgr/conversations/messages/src/lib/message.interface.ts
Solve duplicate messages bug on the send message handler by setting the right message direction when saving messages from the bot
=> 🐛 💬 Solve duplicate messages bug

angular.json, apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/elements/theming/_theme.scss, libs/features/convs-mgr/stories/blocks/library/event-block/.eslintrc.json, libs/features/convs-mgr/stories/blocks/library/event-block/README.md, libs/features/convs-mgr/stories/blocks/library/event-block/jest.config.ts, libs/features/convs-mgr/stories/blocks/library/event-block/src/index.ts, libs/features/convs-mgr/stories/blocks/library/event-block/src/lib/components/event-block/event-block.component.html, libs/features/convs-mgr/stories/blocks/library/event-block/src/lib/components/event-block/event-block.component.scss, libs/features/convs-mgr/stories/blocks/library/event-block/src/lib/components/event-block/event-block.component.ts, libs/features/convs-mgr/stories/blocks/library/event-block/src/lib/convs-mgr-event-block.module.ts, libs/features/convs-mgr/stories/blocks/library/event-block/src/test-setup.ts, libs/features/convs-mgr/stories/blocks/library/event-block/tsconfig.json, libs/features/convs-mgr/stories/blocks/library/event-block/tsconfig.lib.json, libs/features/convs-mgr/stories/blocks/library/event-block/tsconfig.spec.json, libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/event-block-form.model.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/event-block.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/fetch-active-block-component.function.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-types.enum.ts, libs/model/convs-mgr/stories/blocks/messaging/src/index.ts, libs/model/convs-mgr/stories/blocks/messaging/src/lib/event-block.interface.ts, tsconfig.base.json
This PR creates the events brick and correctly saves the object to the database as per the issue #400 
Fixes #400 
* Hardware:
* Toolchain:
* SDK:
=> 🧱 Create Events Brick

libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.html, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.scss, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block.interface.ts
I worked alone.
This pull request solves issue #357, whereby I have redesigned the Block List UI following the design's guidelines.
Fixes #357
https://user-images.githubusercontent.com/85155606/232036914-31dc1ff3-182c-44ef-9ffe-112f6be9e5ab.mp4
-  [x] I have added tests that prove my fix is effective or that my feature works
=> :art: Rework Block List UI

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html, libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.html, libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts, libs/features/convs-mgr/conversations/messaging/src/index.ts, libs/features/convs-mgr/conversations/messaging/src/lib/components/chat-message/chat-message.component.scss, libs/features/convs-mgr/conversations/messaging/src/lib/components/messages-container/messages-container.component.html, libs/features/convs-mgr/conversations/messaging/src/lib/components/messages-container/messages-container.component.scss, libs/features/convs-mgr/conversations/messaging/src/lib/components/messages-container/messages-container.component.ts, libs/features/convs-mgr/conversations/messaging/src/lib/convs-mgr-conversations-messaging.module.ts, libs/features/convs-mgr/conversations/messaging/src/lib/directives/scroll-position.directive.ts, libs/features/convs-mgr/conversations/messaging/src/lib/providers/spinner.service.ts, libs/features/convs-mgr/stories/home/src/lib/stories.router.ts
This PR fixes a few bugs around the chat message container section. These changes include 
- Infinity Scroll section around the chart area.
- Dynamically show the new message button.
- Show loader when unblocking user.
=> ✨ 🐛 fix Infinity Scroll on Chat section and Add spinner while unblocking users

libs/features/analytics/group-based/progress/src/lib/components/group-based-progress-chart/group-based-progress-chart.component.ts, libs/functions/analytics/progress/main/src/lib/measure-group-progress.handler.ts
Show milestone for current users
=> :bug: fix: show milestone for current users

libs/elements/layout/modals/src/lib/error-prompt-modal/error-prompt-modal.component.html, libs/elements/layout/modals/src/lib/error-prompt-modal/error-prompt-modal.component.scss, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.html, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #305
[Screencast from 18-04-23 15:29:34.webm](https://user-images.githubusercontent.com/109944021/232778449-a386e9cf-a8f3-4f52-94bc-4c5d6144fe3e.webm)
I have checked with multiple blocks that have test areas and they are working as required
=> :art: :memo: Add validation for text fields on blocks #305

libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/index.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/assessment-brick-edit/assessment-brick-edit.component.html, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/assessment-brick-edit/assessment-brick-edit.component.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/convs-mgr-edit-block-module.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/fetch-active-block-component.function.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-types.enum.ts
This pull request creates a edit side bar for the assessment brick
This is in collaboration with and pulled from the pull request #435 
=> ✏️  Assessment edit block modal

libs/elements/layout/page-convl/src/lib/components/convl-page/convl-page.component.scss, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/editor/src/index.ts, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.html, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.scss, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/side-screen-toggle.service.ts
I worked alone.
This pull request solves issue #450, whereby I have redesigned the Block List UI following the design's guidelines.
Fixes #450
https://user-images.githubusercontent.com/85155606/236444161-39ad5eff-0884-48ed-8b4f-0d7e1bcbc544.mp4
-  [x] I have added tests that prove my fix is effective or that my feature works
=> :lipstick: :computer: Increase Side Screen Size 

libs/functions/bot-engine/main/src/lib/services/data-services/channel-info.service.ts, libs/functions/bot-engine/messenger/src/lib/io/incoming-message-parser/message-types/messenger-incoming-image.parser.ts, libs/functions/bot-engine/messenger/src/lib/io/incoming-message-parser/message-types/messenger-incoming-interactive.parser.ts, libs/functions/bot-engine/messenger/src/lib/io/incoming-message-parser/messenger-api-incoming-message-parser.class.ts, libs/functions/bot-engine/messenger/src/lib/io/outgoing-message-parser/messenger-api-outgoing-message-parser.class.ts, libs/functions/bot-engine/messenger/src/lib/messenger-receive-message.handler.ts, libs/functions/bot-engine/messenger/src/lib/utils/convert-messanger-payload.util.ts, libs/model/convs-mgr/functions/src/index.ts, libs/model/convs-mgr/functions/src/lib/messenger/incoming-messenger-message.interface.ts, libs/model/convs-mgr/functions/src/lib/messenger/messenger-attachment-message-out.interface.ts, libs/model/convs-mgr/functions/src/lib/messenger/messenger-button-message-out.interface.ts
This PR implements parsing of media messages to and from the messenger platform.
=> 🤖 ✨ 🎥  Implement parsing of media in messenger

libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts, libs/functions/bot-engine/main/src/lib/services/data-services/channel-info.service.ts, libs/functions/bot-engine/main/src/lib/services/data-services/messages.service.ts, libs/functions/bot-engine/main/src/lib/services/process-input/block-type/process-options-input.service.ts, libs/functions/bot-engine/main/src/lib/services/process-message/process-message.service.ts, libs/functions/bot-engine/messenger/src/lib/io/incoming-message-parser/message-types/messenger-incoming-image.parser.ts, libs/functions/bot-engine/messenger/src/lib/io/incoming-message-parser/message-types/messenger-incoming-interactive.parser.ts, libs/functions/bot-engine/messenger/src/lib/io/incoming-message-parser/message-types/messenger-incoming-text.parser.ts, libs/functions/bot-engine/messenger/src/lib/io/incoming-message-parser/messenger-api-incoming-message-parser.class.ts, libs/functions/bot-engine/messenger/src/lib/io/outgoing-message-parser/messenger-api-outgoing-message-parser.class.ts, libs/functions/bot-engine/messenger/src/lib/messenger-receive-message.handler.ts, libs/functions/bot-engine/messenger/src/lib/utils/convert-messanger-payload.util.ts, libs/model/convs-mgr/functions/src/index.ts, libs/model/convs-mgr/functions/src/lib/messenger/incoming-messenger-message.interface.ts, libs/model/convs-mgr/functions/src/lib/messenger/messenger-attachment-message-out.interface.ts, libs/model/convs-mgr/functions/src/lib/messenger/messenger-attachment-types.enum.ts, libs/model/convs-mgr/functions/src/lib/messenger/messenger-button-message-out.interface.ts, libs/model/convs-mgr/functions/src/lib/messenger/messenger-button-types.enum.ts, libs/model/convs-mgr/functions/src/lib/messenger/messenger-template-types.enum.ts, libs/model/convs-mgr/functions/src/lib/messenger/messsenger-list-message-out.interface.ts
This PR implements parsing of list messages to and from the messenger platform.
=> 🤖 ✨ 📜  Parse lists on messenger

libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/video-message-block/src/index.ts, libs/features/convs-mgr/stories/blocks/library/video-message-block/src/lib/convs-mgr-video-message-block.module.ts
This pull request solves issue #483 that allows the user to edit the uploaded video in the video block.
fixes #483
=> ✨ feat: edit button allows user to edit video.

libs/functions/bot-engine/main/src/lib/services/process-input/block-type/process-media-input.service.ts, libs/functions/bot-engine/main/src/lib/services/process-input/block-type/process-options-input.service.ts, libs/functions/bot-engine/main/src/lib/services/process-input/block-type/process-text-input.service.ts, libs/functions/bot-engine/main/src/lib/services/process-input/process-input.class.ts
Fix non-empty property error on saving user input. Added check for a non-empty string on the storyblock variable name
=> 🐛 Fix non-empty property error on saving user input

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/stories/blocks/library/jump-story-block/src/lib/components/jump-block/jump-block.component.html, libs/features/convs-mgr/stories/blocks/library/jump-story-block/src/lib/components/jump-block/jump-block.component.scss
#501 This Pull request resolves the issue of jump block from dropdown to input textfield.
Reference the issue related to this PR as shown below. Every issue has it's own number you can find the issue numbers [here](https://github.com/italanta/elewa/issues/501).
Fixes  #501
=> 💄 Changed the jump block fromdropdown to input text field.

libs/functions/bot-engine/main/src/lib/services/process-operation-block/block-type/event-block.service.ts, libs/functions/bot-engine/main/src/lib/services/process-operation-block/process-operation-block.factory.ts, libs/model/convs-mgr/conversations/admin/system/src/index.ts, libs/model/convs-mgr/conversations/admin/system/src/lib/event.interface.ts, libs/model/convs-mgr/conversations/admin/system/src/lib/events-stack.interface.ts
This PR implements the Backend Service for the events block (we use it to track when our users reach certain parts of the course or achieve certain objectives).
=> 🏠 ✨ Events brick backend service

libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.html, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/convs-mgr-assessment-brick.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/assessment-brick-form.model.ts, libs/functions/bot-engine/main/src/lib/io/outgoing-message.parser.ts, libs/functions/bot-engine/main/src/lib/services/next-block/block-type/default-block.service.ts, libs/functions/bot-engine/main/src/lib/services/process-message/process-message.service.ts, libs/functions/bot-engine/main/src/lib/services/process-operation-block/block-type/assess-user-answer.ts, libs/functions/bot-engine/main/src/lib/services/process-operation-block/block-type/assessment-block.service.ts, libs/functions/bot-engine/main/src/lib/services/process-operation-block/block-type/assessment-question.service.ts, libs/functions/bot-engine/main/src/lib/services/process-operation-block/block-type/end-story-block.service.ts, libs/functions/bot-engine/main/src/lib/services/process-operation-block/process-operation-block.factory.ts, libs/model/convs-mgr/conversations/admin/system/src/lib/assessment-cursor.interface.ts, libs/model/convs-mgr/conversations/assessments/src/lib/assessment.interface.ts, libs/state/convs-mgr/conversations/assessments/src/lib/services/assessment-publish.service.ts
Bug fixes of the assessment feature. Both front end and backend. The assesment feature should now be able to:
- Mark the assessment and get the final score in percentage
- Redirect the candidate to the next block in the story based on their final score
- Mark the end of an assessment
=> 🐛 🤖 🎨 Assessment feature fixes

angular.json, apps/conv-learning-manager/src/app/app.module.ts, apps/conv-learning-manager/src/app/app.routing.module.ts, apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/elements/theming/_variables.scss, libs/features/convs-mgr/conversations/assessments/src/lib/assessments.router.module.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/convs-mgr-assessments.module.ts, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.ts, libs/state/convs-mgr/end-users/.eslintrc.json, libs/state/convs-mgr/end-users/README.md, libs/state/convs-mgr/end-users/jest.config.ts, libs/state/convs-mgr/end-users/src/index.ts, libs/state/convs-mgr/end-users/src/lib/end-user-state.module.ts, libs/state/convs-mgr/end-users/src/lib/models/end-user.model.ts, libs/state/convs-mgr/end-users/src/lib/services/end-user.service.ts, libs/state/convs-mgr/end-users/src/lib/store/end-user.store.ts, libs/state/convs-mgr/end-users/src/test-setup.ts, libs/state/convs-mgr/end-users/tsconfig.json, libs/state/convs-mgr/end-users/tsconfig.lib.json, libs/state/convs-mgr/end-users/tsconfig.spec.json, tsconfig.base.json
=> 🚧 💯   Assessment results Page.

libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.ts, libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.ts, libs/functions/bot-engine/main/src/lib/services/process-operation-block/block-type/end-story-block.service.ts, libs/model/convs-mgr/stories/main/src/lib/story.interface.ts, libs/state/convs-mgr/conversations/assessments/src/lib/services/assessment-publish.service.ts, libs/state/convs-mgr/stories/block-connections/src/lib/stores/story-connections.store.ts, libs/state/convs-mgr/stories/blocks/src/lib/stores/story-blocks.store.ts
Changes:
- Assessment publish now updates the blocks and connections if a question has been deleted or added
=> :art: :sparkles: :horse_racing: Improvements on assessment publish

libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.scss, libs/model/convs-mgr/stories/blocks/messaging/src/lib/assessment-question-block.interface.ts, libs/state/convs-mgr/conversations/assessments/src/lib/services/assessment-publish.service.ts
This pull request implements the feedback feature on each question. If configured, feedback is sent back to the user after each question.
=> ✨ 🎨 🗣️ Implement feedback on questions

libs/model/convs-mgr/stories/blocks/messaging/src/lib/assessment-question-block.interface.ts, libs/state/convs-mgr/conversations/assessments/src/lib/services/assessment-publish.service.ts, libs/state/convs-mgr/stories/block-connections/src/lib/stores/story-connections.store.ts, libs/state/convs-mgr/stories/blocks/src/lib/stores/story-blocks.store.ts
This pr fixes the issue of the feedback block not being created on the backend on publish.
=> 🐛 Fix feedback on questions not working

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/convs-mgr-assessments.module.ts, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts, libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-toggle-state.service.ts, libs/model/convs-mgr/conversations/assessments/src/lib/assessment-questions.interface.ts
This PR adds a few updates to the assessment feature 
- Adding conditions to assessment feedback.
- A spinner on save and publish.
- A confirmation toast.
- The user is not allowed to publish if the assessment is not saved or there are changes since the last save.
=> ❌❔Prevent Publishing of Assessment If Changes Exist After Last Save.

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessments-home/assessments-home.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessments-home/assessments-home.component.scss
This pr improves the UI of the assessment list page as shown below:
=> 🎨 📈 Assessment list UI improvements

libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.scss
A redesign of the list page to reflex the given product design
Fixes #533 
All functionality maintained:
=> :cookie: :chart_with_upwards_trend: :scroll: Improvement on the Assessment List Page #533

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.scss
- This PR resolves issue #530. 
- Image placeholders and the edit assessment button have been added in this issue.
Fixes #530 
* Hardware:
* Toolchain:
* SDK:
=> :art: :chart_with_upwards_trend:  :triangular_ruler: Update Assessment Results Page Layout and Design #530

apps/conv-learning-manager/src/app/app.module.ts, libs/elements/layout/page-convl/src/lib/components/convl-page/convl-page.component.ts, package.json
This PR integrates intercom on the CLM
=> 🗣️ ✨ Integrate intercom

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.ts, libs/state/convs-mgr/end-users/src/lib/models/end-user.model.ts
This pr computes and visualises the metrics on the results page.
Fixes #529, #531
=> 🎨🔢📈 Compute And Visualise Metrics On The Assessment Results Page

libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.scss
=> :wrench: :lipstick: style results search bar

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.ts
This PR updates the assessment results page styles.
=> :art: :lipstick: Update Results Page Styles

libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answer/assessment-answer.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answer/assessment-answer.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answers/assessment-answers.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answers/assessment-answers.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-forms/assessment-question-forms.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-questions/assessment-questions.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-questions/assessment-questions.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.ts
This PR fixes a few bugs around creating, deleting and updating assessments. 
=> :recycle: :bug: Fix CRUD Operations Around Managing Assessments and their State

libs/elements/theming/_variables.scss, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.ts
This pull request updates the styling on the results page to match the proposed design.
=> 🔀 💄 Update styling on results page

libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answer/assessment-answer.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answer/assessment-answer.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answer/assessment-answer.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts, libs/model/convs-mgr/conversations/assessments/src/lib/assessment-questions.interface.ts, libs/state/convs-mgr/end-users/src/lib/models/end-user.model.ts
This PR adds the percentage score to the label tooltip on hover and also implements the following changes 
- Moves feedback option to choice item.
- Fixes Assessment title returning undefined on page reload.
- Fixes the lack of sorting on nested fields on the results table.
Fixes #543 
=> 🔢 ⏲️ Add Percentage To Label Tooltip And Update Assessment Choices

apps/conv-learning-manager/src/assets/i18n/en.json, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
A more intuitive redesign of the side menu to reflect the given design and add onto features 
Fixes #549
Features work as desired and generate no new warnings on the console.
=> :art: Update main side panel menu items #549

libs/features/convs-mgr/conversations/assessments/src/lib/modals/create-assessment-modal/create-assessment-modal.component.ts, libs/model/convs-mgr/stories/main/src/lib/story.interface.ts
Remove redundant assessment name field
=> 🔥 Remove redundant assessment name field

angular.json, libs/features/convs-mgr/stories/editor/src/lib/modals/add-bot-to-channel-modal/add-bot-to-channel.modal.ts, libs/state/convs-mgr/stories/main/src/lib/stores/stories.store.ts, libs/state/file/store/src/lib/providers/file-storage.service.ts, libs/state/file/whatsapp/.eslintrc.json, libs/state/file/whatsapp/README.md, libs/state/file/whatsapp/jest.config.ts, libs/state/file/whatsapp/src/index.ts, libs/state/file/whatsapp/src/lib/services/whatsapp-upload-file.service.ts, libs/state/file/whatsapp/src/lib/state-file-whatsapp.module.ts, libs/state/file/whatsapp/src/test-setup.ts, libs/state/file/whatsapp/tsconfig.json, libs/state/file/whatsapp/tsconfig.lib.json, libs/state/file/whatsapp/tsconfig.spec.json, tsconfig.base.json
This PR implements uploading of a story media to whatsapp when a user publishes the story. It also updates the story with a publishedOn date.
=>  📹 ⬆️ CLM-78 Upload media to whatsapp on publish story

libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.html, libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.ts
Quick Fix: leaner's tab style update
=> 💄 🎨 CLM-2 Learner's Tab Style Update

libs/features/convs-mgr/learners/src/lib/components/learner-information/learner-information.component.ts
Fixed the go to chat button bug for the single learner page.
Fixes bug in the CLM-7-Learner-profile-page
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the style guidelines of this project
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings
=> :bug: CLM-7 Fixed the go to whatsapp button bug

libs/features/convs-mgr/learners/src/lib/components/learner-information/learner-information.component.ts, libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.scss, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/story-editor-initialiser.service.ts, libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts
This aims to fix the endless scroll issue
#CLM-20-Endless-Scroll
Fixes #515 
- [ X] My code follows the style guidelines of this project
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings
=> :bug:  CLM-20-Endless-Scroll

libs/features/convs-mgr/home/src/lib/components/home-courses/home-courses.component.html, libs/features/convs-mgr/home/src/lib/components/home-courses/home-courses.component.scss, libs/features/convs-mgr/home/src/lib/components/home-courses/home-courses.component.ts, libs/features/convs-mgr/home/src/lib/components/home-summaries/home-summaries.component.html, libs/features/convs-mgr/home/src/lib/components/interesting-events/interesting-events.component.html, libs/features/convs-mgr/home/src/lib/pages/home/home.page.html
Bug Fixes
[Issue](https://elewake.atlassian.net/browse/CLM-148?atlOrigin=eyJpIjoiMWYyYTQxMjU3NjlhNGE1OGFhMWFhOGJhNGUyZThlOTQiLCJwIjoiaiJ9)
=> Home page redesign

libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.scss, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts
Removed the previously added large viewport to fix the zooming bug
- [X ] My code follows the style guidelines of this project
- [X ] My changes generate no new warnings
=> :bug:  Removed the large viewport to fix the zoom bug

libs/state/convs-mgr/conversations/chats/src/lib/stores/chats.store.ts
=> :fire: hotfix

libs/state/convs-mgr/conversations/messages/src/lib/queries/messages.query.ts
=> :fire: :fire: messages store

angular.json, apps/conv-learning-manager/src/app/app.routing.module.ts, apps/conv-lm-backend/src/app/organisation/on-create-org-assign-user-to-org.function.ts, apps/conv-lm-backend/src/main.ts, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.ts, libs/private/features/convs-mgr/orgs/.eslintrc.json, libs/private/features/convs-mgr/orgs/README.md, libs/private/features/convs-mgr/orgs/jest.config.ts, libs/private/features/convs-mgr/orgs/src/index.ts, libs/private/features/convs-mgr/orgs/src/lib/organisation.module.ts, libs/private/features/convs-mgr/orgs/src/lib/organisation.router.ts, libs/private/features/convs-mgr/orgs/src/lib/pages/orgs-pages/orgs-pages.component.html, libs/private/features/convs-mgr/orgs/src/lib/pages/orgs-pages/orgs-pages.component.scss, libs/private/features/convs-mgr/orgs/src/lib/pages/orgs-pages/orgs-pages.component.ts, libs/private/features/convs-mgr/orgs/src/test-setup.ts, libs/private/features/convs-mgr/orgs/tsconfig.json, libs/private/features/convs-mgr/orgs/tsconfig.lib.json, libs/private/features/convs-mgr/orgs/tsconfig.spec.json, libs/private/functions/organisation/src/lib/assign-user-to-created-org.handler.ts, tsconfig.base.json
Adds update to ask users to create an account if they do not have one.
=> Request org create for new users

libs/functions/convs-mgr/story-editor/check-story-for-errors/src/lib/check-story-for-errors.handler.ts
pass the blocks directly instead of querying the db
#594 CLM-136
- [ X] New feature (non-breaking change which adds functionality)
- [X ] My code follows the style guidelines of this project
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings
- [ X] Any dependent changes have been merged and published in downstream modules
=> :rocket:  CLM-136:  Backend Function to Validate the Story and Return Errors#2

angular.json, apps/conv-learning-manager/src/app/app.routing.module.ts, apps/conv-lm-backend/src/app/organisation/on-create-org-assign-user-to-org.function.ts, apps/conv-lm-backend/src/main.ts, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.ts, libs/private/features/convs-mgr/orgs/.eslintrc.json, libs/private/features/convs-mgr/orgs/README.md, libs/private/features/convs-mgr/orgs/jest.config.ts, libs/private/features/convs-mgr/orgs/src/index.ts, libs/private/features/convs-mgr/orgs/src/lib/organisation.module.ts, libs/private/features/convs-mgr/orgs/src/lib/organisation.router.ts, libs/private/features/convs-mgr/orgs/src/lib/pages/orgs-pages/orgs-pages.component.html, libs/private/features/convs-mgr/orgs/src/lib/pages/orgs-pages/orgs-pages.component.scss, libs/private/features/convs-mgr/orgs/src/lib/pages/orgs-pages/orgs-pages.component.ts, libs/private/features/convs-mgr/orgs/src/test-setup.ts, libs/private/features/convs-mgr/orgs/tsconfig.json, libs/private/features/convs-mgr/orgs/tsconfig.lib.json, libs/private/features/convs-mgr/orgs/tsconfig.spec.json, libs/private/functions/organisation/src/lib/assign-user-to-created-org.handler.ts, tsconfig.base.json
Lost changes from request create org
=> :wrench: Lost Create Org Changes

SETUP.md
This PR fixes a typo in the SETUP.md file
Fixes #629
=> :pencil2: fix typo in SETUP.md

angular.json, libs/features/convs-mgr/learners/src/lib/convs-mgr-learners.module.ts, libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.ts, libs/model/convs-mgr/functions/src/lib/base/message-template.interface.ts, libs/model/convs-mgr/functions/src/lib/base/schedule/send-message-template.interface.ts, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.html, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.scss, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-list/message-template-list.component.html, libs/private/features/convs-mgr/message-templates/src/lib/convs-mgr-message-templates.module.ts, libs/private/features/convs-mgr/message-templates/src/lib/providers/create-empty-message-template-form.provider.ts, libs/private/state/message-templates/src/lib/private-state-message-templates.module.ts, libs/private/state/message-templates/src/lib/service/message-template.service.ts, libs/private/state/message-templates/src/lib/service/schedule-message.service.ts, libs/private/state/organisation/channels/.eslintrc.json, libs/private/state/organisation/channels/README.md, libs/private/state/organisation/channels/jest.config.ts, libs/private/state/organisation/channels/src/index.ts, libs/private/state/organisation/channels/src/lib/organisation-channels.module.ts, libs/private/state/organisation/channels/src/lib/private-state-organisation-channels.module.ts, libs/private/state/organisation/channels/src/lib/services/channel.service.ts, libs/private/state/organisation/channels/src/lib/store/channel.store.ts, libs/private/state/organisation/channels/src/test-setup.ts, libs/private/state/organisation/channels/tsconfig.json, libs/private/state/organisation/channels/tsconfig.lib.json, libs/private/state/organisation/channels/tsconfig.spec.json, tsconfig.base.json
=> :floppy_disk:  :wrench:  channel store and service

libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-list/message-template-list.component.ts, libs/private/state/message-templates/src/lib/service/message-template.service.ts
=> Channel service

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-forms/assessment-question-forms.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-forms/assessment-question-forms.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessments-grid-view/assessments-grid-view.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessments-list-view/assessments-list-view.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessments-list-view/assessments-list-view.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessments-list-view/assessments-list-view.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/create-assessment-flow/create-assessment-page/create-assessment-page.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/create-assessment-flow/create-assessment-page/create-assessment-page.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/create-assessment-flow/create-assessment-page/create-assessment-page.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/convs-mgr-assessments.module.ts, libs/features/convs-mgr/conversations/assessments/src/lib/model/questions-form.model.ts, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/providers/create-empty-assessment-form.provider.ts, libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts, libs/model/convs-mgr/conversations/assessments/src/lib/assessment.interface.ts, libs/state/convs-mgr/conversations/assessments/src/lib/services/assessment.service.ts, libs/state/convs-mgr/conversations/assessments/src/lib/stores/active-assessment.store.ts
Updated assessments view design
=> CLM-142 Updated assessments view

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/elements/theming/_variables.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/analytics-settings/analytics-settings.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/components/analytics-settings/analytics-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/assessment-settings/assessment-settings.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/components/assessment-settings/assessment-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/bots-settings/bots-settings.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/components/bots-settings/bots-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/chats-settings/chats-settings.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/components/chats-settings/chats-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/general-settings/general-settings.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/components/general-settings/general-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/learner-settings/learner-settings.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/components/learner-settings/learner-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/permissions/permissions.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/components/permissions/permissions.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/permissions/permissions.component.ts, libs/private/features/convs-mgr/settings/permissions/src/lib/modals/add-new-org-role-modal/add-new-org-role-modal.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/modals/delete-org-role-modal/delete-org-role-modal.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/modals/switch-button/switch-button.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/modals/switch-button/switch-button.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/modals/switch-button/switch-button.component.spec.ts, libs/private/features/convs-mgr/settings/permissions/src/lib/modals/switch-button/switch-button.component.ts, libs/private/features/convs-mgr/settings/permissions/src/lib/permissions-settings.module.ts
In this pr , the permissions code was redesigned and a new button added.
=> 💄 CLM-197 Redesigned Permissions Page

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/elements/theming/_variables.scss, libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.html, libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.scss, libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.ts, libs/private/state/organisation/main/src/lib/services/organisation.service.ts
In this pr, the company information page was redesigned.
=> 💄CLM-198 Redesign Company Information Page

libs/features/convs-mgr/home/src/lib/components/home-analysis-content/home-analysis-content.component.html, libs/features/convs-mgr/home/src/lib/components/home-summaries/home-summaries.component.html, libs/features/convs-mgr/home/src/lib/components/home-summaries/home-summaries.component.ts, libs/features/convs-mgr/home/src/lib/pages/home/home.page.html, libs/functions/bot-engine/main/src/lib/services/next-block/block-type/default-block.service.ts, libs/functions/bot-engine/main/src/lib/services/next-block/block-type/multiple-options-block.service.ts, libs/functions/bot-engine/main/src/lib/services/next-block/next-block.class.ts, libs/functions/bot-engine/main/src/lib/services/process-message/process-message.service.ts
Replaces the static content on the home page and disables the other static sections for now
* Hardware:
* Toolchain:
* SDK:
=> CLM-148 Home page fixes

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.html, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.scss, libs/features/convs-mgr/home/src/lib/pages/home/home.page.html, libs/features/convs-mgr/stories/home/src/lib/components/labels/labels.component.html, libs/features/convs-mgr/stories/home/src/lib/pages/stories-dashboard/stories-dashboard.component.html
Fixes a few minor issues to do with the side panel labelling and login logo.
=> CLM-140 CLM-103 sidenav redesign & Login Logo size fix

apps/conv-learning-manager/src/assets/i18n/en.json, libs/private/features/convs-mgr/settings/billing/src/lib/components/billing/billing.component.html
=> Multi lang billing

libs/private/features/convs-mgr/settings/billing/src/lib/components/billing/billing.component.html, libs/private/features/convs-mgr/settings/billing/src/lib/components/billing/billing.component.scss
I have changed the units from px to vh to solve resolution problems
=> 💄 Billings Page Resolutions fix

apps/conv-learning-manager/src/assets/i18n/en.json, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.html, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.scss
CLM 251
templates issues when creating templates.
=> :art: Clm-251 templates issues when creating templates

libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-header/message-template-header.component.html, libs/private/features/convs-mgr/message-templates/src/lib/message-template.router.ts
CLM-249
#249
Delete template info and icon
=> :fire: Clm 249 templates delete the info icon and related page for now

libs/features/convs-mgr/conversations/chats/src/lib/components/chats-list/chats-list.component.html
Changed placeholder name from chats to assessments
=> 💄Change search bar placeholder name #243

libs/elements/theming/_variables.scss, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.html, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.scss
This PR makes minor UI changes to sign up page
Fixes #745
=> 🎨Sign up design changes.

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
Changed messaging cursor to pointer
=> 💄Changed Messaging Cursor to pointer #241

libs/features/convs-mgr/stories/home/src/lib/components/bots-list-header/bots-list-header.component.html, libs/features/convs-mgr/stories/home/src/lib/components/bots-list-header/bots-list-header.component.scss
=> :lipstick:  CLM-255: white overlay

libs/features/convs-mgr/conversations/assessments/src/lib/components/assessments-list-view/assessments-list-view.component.html
=> :art: :bug:  CLM-259: Assessment layout fix

libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.html
=> 🎨 CLM-245 remove chat detail header

libs/features/convs-mgr/conversations/surveys/src/lib/pages/survey-responses/survey-responses.component.html, libs/features/convs-mgr/conversations/surveys/src/lib/pages/survey-responses/survey-responses.component.ts
CLM-263
Send reminder does not work as there is no current implementation for it so I temporarily removed the link. The whole page is full of placeholder data.
=> :loud_sound:   Clm 263 surveys send reminder button doesn t work

libs/features/convs-mgr/conversations/surveys/src/lib/components/create-survey-flow/create-survey-flow.component.ts
send survey was showing two popups one for publihing and an error one if user has not selected the channel. I have removed the publishing one so as to publish in the background.
=> :art:  removed the snackbar for publishing

libs/elements/layout/toast/src/lib/components/toast/toast.component.scss, libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.html, libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.ts, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts, libs/private/state/organisation/main/src/lib/services/organisation.service.ts
CLM-310, CLM-309, CLM-277, CLM-297, CLM-275
Bug fixes:
Hover over error message turned to pointer.
Company detail prefill bug.
Paginator for learnerss page.
Connection Error not hyper linked.
=> :bug: Settings page and company info page bugs

libs/private/features/convs-mgr/settings/users/src/lib/components/users/users.component.ts
CLM-302 members sorting by name bug fixed.
=> :bug:  case insensitive sorting

libs/features/convs-mgr/conversations/surveys/src/lib/components/survey-list-view/survey-list-view.component.html
CLM-317
Added survey question count
=> :bug:  CLM-317: Survey Count Added

libs/features/convs-mgr/conversations/surveys/src/lib/components/survey-header/survey-header.component.html
survey create bug.
There was a white overlay which i think is for the backdrop
=> :fire:  removed overlay in the meantime

libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts, libs/state/convs-mgr/story-editor/src/lib/providers/check-story-errors.service.ts
This pr fixes the bug where the state is not refreshed when checking for errors.
=> 🐛  Check story for errors

libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts
I have commented to sticker block module to hide it.
=> 🔥Make Bots-sticker-block Not Visible  #CLM-316

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
I have fixed double bubble on some icons on hover. I removed the matTooltip
=> 💄  Fixed Double Bubble on some icons on hover #CLM-315

libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.ts, libs/private/features/convs-mgr/orgs/src/lib/pages/orgs-pages/orgs-pages.component.ts
For this change, i moved the org check from the orgs page to the auth page, to prevent temporary showing of the organization page when logging in.
=> 🐛 Removed Temporary org page from showing#CLM-216

apps/conv-learning-manager/src/assets/icons/arrow-down.svg, apps/conv-learning-manager/src/assets/icons/arrow-up.svg, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.ts
=> Revert ":lipstick: feat: CLM 322 collapse chats and templates sub menu into messaging #787"

libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.html, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.scss, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts
Removed the publish button at the top of editor page for users not to attempt publishing since they can't here
Fixes #321
=> 💄Removed Publish Button From Story Editor #CLM-321

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
Aligned the words to the center of the icons.
Fixes #786 🎨💄CLM-323-Align wording and menu icons
* Hardware:
* Toolchain:
* SDK:
=> 🎨💄CLM-323-Align wording and menu icons #786

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-metrics.service.ts, libs/features/monitoring/src/lib/components/assessment-progress-chart/assessment-progress-chart.component.html, libs/features/monitoring/src/lib/components/enrolled-user-progress-chart/enrolled-user-progress-chart.component.html, libs/features/monitoring/src/lib/components/enrolled-user-progress-chart/enrolled-user-progress-chart.component.scss, libs/features/monitoring/src/lib/components/enrolled-user-progress-chart/enrolled-user-progress-chart.component.ts, libs/features/monitoring/src/lib/components/group-based-progress-chart/group-based-progress-chart.component.html, libs/features/monitoring/src/lib/components/group-based-progress-chart/group-based-progress-chart.component.scss, libs/features/monitoring/src/lib/components/group-based-progress-chart/group-based-progress-chart.component.ts, libs/features/monitoring/src/lib/providers/helper-fns.util.ts, libs/functions/bot-engine/main/src/lib/services/data-services/cursor.service.ts, libs/functions/bot-engine/main/src/lib/services/data-services/enrolled-user.service.ts, libs/model/analytics/group-based/progress/src/index.ts, libs/model/analytics/group-based/progress/src/lib/analytics-config.model.ts, libs/model/analytics/group-based/progress/src/lib/group-progress.model.ts, libs/model/analytics/group-based/progress/src/lib/measure-group-progress.command.ts, libs/model/analytics/group-based/progress/src/lib/measure-progress.command.ts, libs/model/analytics/group-based/progress/src/lib/participant-progress.model.ts, libs/model/convs-mgr/classroom/src/lib/classroom.interface.ts, libs/private/features/convs-mgr/analytics/src/lib/pages/dashboard-page/dashboard-page.component.html, libs/private/features/convs-mgr/analytics/src/lib/pages/dashboard-page/dashboard-page.component.ts, libs/private/features/convs-mgr/analytics/src/lib/utils/mock.data.ts, libs/private/functions/analytics/progress/main/src/lib/data-services/monitoring.service.ts, libs/private/functions/analytics/progress/main/src/lib/handlers/measure-group-progress.handler.ts, libs/private/functions/analytics/progress/main/src/lib/handlers/measure-participant-progress.handler.ts
This PR adds necessary updates, optimisations and cleanups to the progress monitoring visualisation handlers and component rendering of the chart data.
NB: data is now grouped by Id (class Id, course Id, etc) so existing visuals will have to be recomputed. This is however simple as we can calculate all past data.
=> 🔥:sparkles:  perf: monitoring and visualisation updates

libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.ts, libs/state/convs-mgr/channels/src/lib/services/channel.service.ts
I added a check to ensure that the user's current position includes a  communication channel then before that incorporated a method to hide the spinner before it so a to remove the recurrent long spinning when unblocking the user
=> 💄fixed changes to unblock user on chats #246

libs/private/features/convs-mgr/settings/organisation-details/src/lib/components/company-data/company-data.component.ts, libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/add-channel-modal/add-channel-modal.component.html, libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/add-channel-modal/add-channel-modal.component.ts
Fixed the case of whats app and messenger
=> 🎨 fixed case issue

libs/features/convs-mgr/stories/home/src/lib/pages/courses-view-all-page/courses-view-all-page.component.html
Capitalized  search bar text for 'search course' to an 'S'
=> 💄Fixed search-Bar-Text for Courses #CLM-351

apps/conv-learning-manager/src/assets/i18n/en.json, libs/private/features/convs-mgr/settings/users/src/lib/modals/new-user-dialog/new-user-dialog.component.html
Changed the 'No Thanks ' text on add user in settings to 'Cancel'
=> 💄Fixed text on add user settings #CLM-358

libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.html
Removed repeated texts "Learning Experience " from the Sign up page
=> 💄Removed Repeated Texts on Sign up Page #CLM-347

apps/conv-learning-manager/src/styles.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.ts, libs/features/convs-mgr/modules/src/lib/components/stories-list-header/stories-list-header.component.html, libs/features/convs-mgr/modules/src/lib/components/stories-list-header/stories-list-header.component.scss, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/home/src/lib/components/modules/modules-list-header/modules-list-header.component.html, libs/features/convs-mgr/stories/home/src/lib/components/modules/modules-list-header/modules-list-header.component.scss
the issues fixed are :
1:CLM-353
2: CLM-356
3.CLM-342
Fixes # (issue) - *Example*: Fixes #10, #20 NOTE: GitHub issue numbers should be prefixed with **#** to aid with issue tracking.
=> 🐛 Fixed Bugs From Sprint 5 #CLM-353 #CLM-356 #CLM-342

libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.html, libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.scss
Removed background-color and changed sign-up and login buttons to hyperlinks
=> 💄Changed Login and Sign up buttons to hyper-links #CLM-346

libs/features/convs-mgr/home/src/lib/pages/home/home.page.html, libs/features/convs-mgr/home/src/lib/pages/home/home.page.scss
Added and styled homepage title
=> 💄Added homepage title #CLM-348

libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.html, libs/features/convs-mgr/modules/src/lib/components/stories-list-header/stories-list-header.component.scss, libs/features/convs-mgr/stories/home/src/lib/components/modules/modules-list-header/modules-list-header.component.scss
CLM-356
CLM-353
- [ x Bug fix (non-breaking change which fixes an issue)
=> 🐛 Bug fixes #CLM-356 #CLM-353

libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.scss
Changed and style login and create account buttons to hyperlinks
=> 💄Fixed login and signup links styling #CLM-346

libs/features/app/auth/login/src/lib/pages/auth/auth.page.component.scss
Fixed font-weight for the sign-up text
=> 💄Fixed Sign-up font style #CLM-349

apps/conv-learning-manager/src/assets/i18n/en.json, libs/private/features/convs-mgr/settings/main/src/lib/pages/settings-page/settings-page.component.html
Changed the Label Admin Settings to Settings
=> 💄Fixed-Settings-Label#336

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/components/anchor-block/anchor-block.component.scss, libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/components/end-anchor/end-anchor.component.html, libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/components/end-anchor/end-anchor.component.scss, libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/components/end-anchor/end-anchor.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.scss, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
Added the delete functionality to the end block on user story
=> 💄Added Delete Functionality to the End Block #CLM-325

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-single-settings/message-template-single-settings.component.scss, libs/private/features/convs-mgr/message-templates/src/lib/modals/milestone-reached-modal/milestone-reached-modal.component.html, libs/private/features/convs-mgr/message-templates/src/lib/modals/specific-time-modal/specific-time-modal.component.html, libs/private/features/convs-mgr/message-templates/src/lib/modals/specific-time-modal/specific-time-modal.component.scss, libs/private/features/convs-mgr/message-templates/src/lib/modals/specific-time-modal/specific-time-modal.component.ts
This pr have fixed message template modals design bugs
=> 🐛 Message-templates bug design fixes #CLM-361-

libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.scss, package.json
Removed the white background behind the delete button
=> 💄Removed White Background on Delete Button #CLM-325

libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-list/message-template-list.component.ts, libs/private/features/convs-mgr/message-templates/src/lib/providers/create-empty-message-template-form.provider.ts
This PR refactors and cleans up the message templates local state.
=> 🔥 ♻️ perf: message templates updates

angular.json, apps/conv-learning-manager/src/app/app.module.ts, apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/variable-input/variable-input.component.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/providers/variables.service.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/storyblock-variable.interface.ts, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.html, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.scss, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts, libs/state/convs-mgr/variables/.eslintrc.json, libs/state/convs-mgr/variables/README.md, libs/state/convs-mgr/variables/jest.config.ts, libs/state/convs-mgr/variables/src/index.ts, libs/state/convs-mgr/variables/src/lib/stores/variable-blocks.store.ts, libs/state/convs-mgr/variables/src/lib/variables.module.ts, libs/state/convs-mgr/variables/src/test-setup.ts, libs/state/convs-mgr/variables/tsconfig.json, libs/state/convs-mgr/variables/tsconfig.lib.json, libs/state/convs-mgr/variables/tsconfig.spec.json, tsconfig.base.json
In this pull required , variable data is being fetched from the bots instead of being inputed manual as previously done
=> 🎨 Enhance message template design #CLM-319

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
Remove tool tip for chats and templates
=> :lipstick: CLM-181 Remove tool tip for chats and templates

libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.html, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.scss
This Pr is correcting some minor ui fixes
=> 🎨💄Enhance message template design clm 319

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/providers/variables.service.ts, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.html, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts
Here i have created a new field to hold header variables
Fixes # (issue) - fixes #CLM-320
=> 💄 Creted a new Variables section for header field #CLM-319

libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.html, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.scss, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts
In this pr , i have changed the bot list style to avoid overlapping and cleaned up the code.
=> 🎨Improved Design of message Template

libs/features/convs-mgr/conversations/assessments/src/lib/components/create-assessment-flow/create-assessment-page/create-assessment-page.component.scss
Removed the line indicator displaying beneath the create and preview buttons on click
=> 💄Removed Line Indicator on create and preview buttons

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/functions/bot-engine/whatsapp/src/lib/services/manage-template-service.class.ts, libs/functions/bot-engine/whatsapp/src/lib/services/map-template-components.ts, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.html, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.scss, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-form/message-template-form.component.ts, libs/private/features/convs-mgr/message-templates/src/lib/providers/create-empty-message-template-form.provider.ts
Here i have fixed the padding of the input boxes.
=> 🐛  fixed font weight and padding of input boxes

libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-latest-courses/bots-list-latest-courses.component.html, libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-latest-courses/bots-list-latest-courses.component.ts, libs/features/convs-mgr/stories/home/src/lib/modals/channel/channel.component.html, libs/features/convs-mgr/stories/home/src/lib/modals/channel/channel.component.scss, libs/features/convs-mgr/stories/home/src/lib/modals/confirm-archive-modal/confirm-archive-modal.component.html, libs/features/convs-mgr/stories/home/src/lib/modals/confirm-archive-modal/confirm-archive-modal.component.scss, libs/features/convs-mgr/stories/home/src/lib/modals/confirm-archive-modal/confirm-archive-modal.component.ts, libs/features/convs-mgr/stories/home/src/lib/modals/confirm-delete-modal/confirm-delete-modal.component.html, libs/features/convs-mgr/stories/home/src/lib/modals/confirm-delete-modal/confirm-delete-modal.component.scss, libs/features/convs-mgr/stories/home/src/lib/modals/confirm-delete-modal/confirm-delete-modal.component.ts, libs/features/convs-mgr/stories/home/src/lib/modals/confirm-publish-modal/confirm-publish-modal.component.html, libs/features/convs-mgr/stories/home/src/lib/modals/confirm-publish-modal/confirm-publish-modal.component.scss, libs/features/convs-mgr/stories/home/src/lib/modals/confirm-publish-modal/confirm-publish-modal.component.ts, libs/features/convs-mgr/stories/home/src/lib/modals/connect-to-channel-modal/connect-to-channel-modal.component.html, libs/features/convs-mgr/stories/home/src/lib/modals/connect-to-channel-modal/connect-to-channel-modal.component.scss, libs/features/convs-mgr/stories/home/src/lib/modals/connect-to-channel-modal/connect-to-channel-modal.component.ts, libs/features/convs-mgr/stories/home/src/lib/modals/main-channel-modal/main-channel-modal.component.scss, libs/features/convs-mgr/stories/home/src/lib/stories-home.module.ts
This PR improves and fixes the styling of connect channel modal
=> 💄 CLM-130 Update styling of connect channel modal

libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts
Allow adding and editing of a variable to the video input block
=> :bug: CLM-388 Allow adding a variable to the video input block

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss, libs/features/convs-mgr/conversations/chats/src/lib/components/chats-list/chats-list.component.scss, libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-all-courses/bots-list-all-courses.component.scss, libs/private/features/convs-mgr/message-templates/src/lib/components/message-template-list/message-template-list.component.scss, libs/private/features/convs-mgr/settings/main/src/lib/pages/settings-page/settings-page.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/analytics-settings/analytics-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/assessment-settings/assessment-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/bots-settings/bots-settings.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/components/bots-settings/bots-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/chats-settings/chats-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/general-settings/general-settings.component.html, libs/private/features/convs-mgr/settings/permissions/src/lib/components/general-settings/general-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/learner-settings/learner-settings.component.scss, libs/private/features/convs-mgr/settings/permissions/src/lib/components/permissions/permissions.component.scss, libs/private/features/convs-mgr/settings/users/src/lib/components/users/users.component.scss
Fixes
CLM-367: Home page
CLM-368: Analytics
CLM-369: Bots
CLM-370: Chats
CLM-371: Message templates
CLM-372: Assessments
CLM-375: Settings (permissions tab, members tab)
=> 💄 UI platform fixes fr

apps/conv-learning-manager/src/styles.scss, libs/elements/theming/_variables.scss, package.json
This PR increases connector width by 1 point and changes the color back to the original one for easy visibility and management
=> 💄 CLM-401 Increase connector thickness

libs/state/convs-mgr/stories/block-connections/src/lib/stores/story-connections.store.ts, libs/state/convs-mgr/story-editor/src/lib/providers/story-editor-state.service.ts
Fixes the bug whereby if you switch to another story, the story editor will still show blocks and connections of the last story.
Also fixes a lot of underlying issues in the story editor, therefore should be reviewed and merged to production as soon as possible.
=> 🐛 ⚡  CLM-407 Open last story bug

libs/features/convs-mgr/modules/src/lib/components/modules-lessons-grid-view/modules-lessons-grid-view.component.scss, libs/features/convs-mgr/stories/home/src/lib/components/courses/courses-list/courses-list.component.scss, libs/features/convs-mgr/stories/home/src/lib/components/modules/bot-modules-grid-view/bot-modules-grid-view.component.scss
Fix overflowing of module, course and lesson name by adding padding around the name
=> :lipstick: CLM-414 Fix overflowing of module, course and lesson name

apps/conv-learning-manager/src/styles.scss, libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/components/end-anchor/end-anchor.component.scss, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.html, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.scss, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.scss, libs/features/convs-mgr/stories/editor/src/lib/components/grouped-blocks/grouped-blocks.component.scss, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.html, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.scss
Styling updates on the story editor to match design
=> 💄 📝 CLM-430 Story editor redesign

libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.html, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.scss, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/providers/decorate-jsplumb.provider.ts
Add JSPlumb connections to the assessment brick to fit the rest of the blocks
=> :bug: Assessment connections bug

libs/features/convs-mgr/conversations/assessments/src/lib/components/all-questions-form/all-questions-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/content-section/content-section.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/single-question-form/single-question-form.component.html
=> :bug: Fix Controls Bug

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
Add background color to a selected tab in the sidenav
=> CLM-513-Sidenav - Highlight remain on tab click

apps/conv-learning-manager/src/assets/i18n/en.json
Update header description to text only.
=> 💬  CLM 483 - Message Templates - header

libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.html, libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.scss, libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.ts
Addition of a spinner to show loading effect when changing the profile image.
=> 💄CLM 494 Settings - Profile Details - Change profile image takes too long

libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-all-courses/bots-list-all-courses.component.html, libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-all-courses/bots-list-all-courses.component.ts, libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.html, libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.ts
Remove type column from courses table
=> 🔥 Clm 452 - Bots - remove "type" column

libs/features/convs-mgr/conversations/chats/src/lib/components/chats-list/chats-list.component.scss, libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.html, libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.scss, libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.ts
Fix dead space at the bottom of the chats page.
Before:
After:
=> 💄 Clm 479 - Chats - fix dead space on the bottom of the page

libs/features/convs-mgr/conversations/assessments/src/lib/components/all-questions-form/all-questions-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/all-questions-form/all-questions-form.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/all-questions-form/all-questions-form.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/single-question-form/single-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/single-question-form/single-question-form.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-preview-page/assessment-preview-page.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/providers/create-empty-assessment-form.provider.ts, libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts
- Fix Story flow configuration does not work
- Implement Images & Video in assessment page
=> :bug: Story Configs Bug

libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.html
=> 🐛 CLM 489 - Users - fix pagination

libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.html, libs/features/convs-mgr/learners/src/lib/utils/learner-filter.util.ts
Fix users platform filter dropdown
=> 🐛 CLM 488 - Users - platform filter not working

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-all-courses/bots-list-all-courses.component.html, libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-all-courses/bots-list-all-courses.component.ts
=> 💄 CLM 452 - Bots - remove "type" column

libs/features/monitoring/src/lib/providers/helper-fns.util.ts
Truncate date label to dd/mmm format
Before:
After:
=> 💄 Clm 475 Analytics - Daily filter

libs/features/monitoring/src/lib/providers/helper-fns.util.ts
Change data labels from week x to the date of the first day of week x
=> 💄CLM 476 - Analytics - Weekly filter

libs/features/convs-mgr/conversations/chats/src/lib/components/chat-card/chat-card.component.html, libs/features/convs-mgr/conversations/chats/src/lib/components/chat-detail-header/chat-detail-header.component.html
=> ✨💄 CLM 526 - Chats - long names messing up the button placement

libs/private/features/convs-mgr/settings/user-profile/src/lib/components/profile-details/profile-details.component.html
Remove delete profile and change password sections
=> 💡 CLM 493 - Settings - Profile Details - remove delete profile button

libs/features/convs-mgr/user-groups/src/lib/components/single-group-user-list/single-group-user-list.component.html, libs/features/convs-mgr/user-groups/src/lib/components/single-group-user-list/single-group-user-list.component.ts
Fix pagination in user groups table
After:
=> 🐛 CLM 521 - User groups - fix pagination

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
=> 💄 CLM 513 - Sidenav - when a tab is selected highlight remains

apps/conv-learning-manager/src/assets/i18n/en.json, libs/private/features/convs-mgr/settings/user-profile/src/lib/components/profile-details/profile-details.component.html, libs/private/features/convs-mgr/settings/user-profile/src/lib/components/profile-details/profile-details.component.scss, libs/private/features/convs-mgr/settings/user-profile/src/lib/components/profile-details/profile-details.component.ts, libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.html, libs/private/features/convs-mgr/settings/user-profile/src/lib/modals/update-profile-picture-modal/update-profile-picture-modal.component.scss
Updated change profile picture modal appearance.
Added remove and upload buttons and functionality to the profile image section on clicking the edit profile button.
Changed page title to “Settings”.
Increased the spacing between the edit profile button and the fields above it.
Change profile picture modal
=> 💄✨ Clm 492 - Settings - Profile details - design changes

libs/features/convs-mgr/stories/home/src/lib/components/courses/course-module-item/course-module-item.component.ts
Update story status based on the published status of its specific bot.
=> 🐛 CLM 529 - Bots - status not updating in View All

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss, libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.scss
=> 💄 CLM 464 - Sidenav - profile icon

libs/state/convs-mgr/learners/src/lib/services/learners.service.ts
Fix active status filter for users
=> 🐛CLM487 - Users - fix active status filter

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/learners/src/lib/modals/change-class/change-class.component.html, libs/features/convs-mgr/learners/src/lib/modals/change-class/change-class.component.scss, libs/features/convs-mgr/learners/src/lib/modals/change-class/change-class.component.ts, libs/features/convs-mgr/learners/src/lib/pages/learners-page/learners-page.component.ts, libs/model/convs-mgr/classroom/src/lib/classroom.interface.ts
Redesign add user to group modal.
Display user's name if a single user is selected.
Display number of selected users if multiple users are selected.
Enable "Apply" button only if a group has been selected.
Disable selected user(s) group from the groups dropdown.
=> ✨💄💬Clm 520 - Users - add user to group modal

libs/private/features/convs-mgr/settings/organisation-details/src/lib/modals/channel-form-modal/channel-form-modal.component.scss
Remove default background color in input fields on autocomplete
=> 💄 CLM 445 - Channel connector modal

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
Increase the spacing between sub menus.
=> 💄CLM 513 - Sidenav - when a tab is selected highlight remains

libs/private/features/convs-mgr/settings/main/src/lib/pages/settings-page/settings-page.component.scss
=> 💄 CLM 492 - Settings - Profile details - design changes

libs/elements/layout/clm-micro-app/src/lib/components/clm-micro-app-page/clm-micro-app-page.component.html, libs/elements/layout/clm-micro-app/src/lib/components/clm-micro-app-page/clm-micro-app-page.component.ts, libs/elements/layout/clm-micro-app/src/lib/components/micro-apps-header/micro-apps-header.component.html, libs/elements/layout/clm-micro-app/src/lib/components/micro-apps-header/micro-apps-header.component.scss, libs/elements/layout/clm-micro-app/src/lib/components/micro-apps-header/micro-apps-header.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/all-questions-form/all-questions-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/all-questions-form/all-questions-form.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-feedback-section/assessment-feedback-section.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/content-section/content-section.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/micro-app-assessment-landing-page/assessment-landing-page.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/single-question-form/single-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-preview-page/assessment-preview-page.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/services/microapp-assessment-questions-form.service.ts, libs/features/convs-mgr/stories/blocks/library/assessment-micro-app/src/lib/components/assessment-micro-app-block/assessment-micro-app-block.component.ts
Work on submit button, logo, and button text
Fixes # [CLM-440]  # [CLM-55]  [CLM-254]
[CLM-440]: https://elewake.atlassian.net/browse/CLM-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLM-55]: https://elewake.atlassian.net/browse/CLM-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLM-254]: https://elewake.atlassian.net/browse/CLM-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Micro apps bug fixes CLM-440, CLM-254 and CLM-55

libs/features/convs-mgr/conversations/assessments/src/index.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/all-questions-form/all-questions-form.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answer/assessment-answer.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answer/assessment-answer.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answer/assessment-answer.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-answers/assessment-answers.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-forms/assessment-question-forms.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-forms/assessment-question-forms.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/model/question-display-mode.enum.ts, libs/features/convs-mgr/conversations/question-banks/src/lib/components/add-question-to-assessment/add-question-to-assessment.component.ts, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-header/question-bank-header.component.ts, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.html, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.ts, libs/model/convs-mgr/conversations/assessments/src/lib/question-form-mode.enum.ts, libs/state/convs-mgr/conversations/assessments/src/lib/services/assessment.service.ts
Fix bugs arising from merging QB to other assessment features.
=> Minor Question Banks Bugs

libs/state/convs-mgr/conversations/chats/src/lib/stores/models/chats-list-state.model.ts
Fix previous page button functionality.
=> 🐛 CLM 479 - Chats - fix dead space on the bottom of the page

libs/features/convs-mgr/user-groups/src/lib/components/user-groups-list/user-groups-list.component.html, libs/features/convs-mgr/user-groups/src/lib/components/user-groups-list/user-groups-list.component.ts
Add sorting functionality to the main **User Groups** table.
=> ✨ Clm 522 - User groups - sorting not working

libs/elements/layout/convs-mgr/custom-components/src/lib/components/custom-dropdown/custom-drop-down.component.html, libs/elements/layout/convs-mgr/custom-components/src/lib/components/custom-dropdown/custom-drop-down.component.scss, libs/features/convs-mgr/learners/src/lib/convs-mgr-learners.module.ts, libs/features/convs-mgr/learners/src/lib/modals/change-class/change-class.component.html, libs/features/convs-mgr/learners/src/lib/modals/change-class/change-class.component.scss, libs/features/convs-mgr/learners/src/lib/modals/change-class/change-class.component.ts
Implement custom dropdown in users modal
=> ✨💄  Clm 520 - Users - add user to group modal

libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/components/anchor-block/anchor-block.component.ts, libs/features/convs-mgr/stories/blocks/library/block-options/src/index.ts, libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/providers/jsplumb-anchor-decorator.function.ts, libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/blocks/library/video-input-block/src/lib/components/video-input-block/video-input-block.component.scss, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts
Redesigned the default connector.
=> 💄 Clm 279 - Bots - fix connector depth in relation to other blocks

libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-results-components/distribution-bar-chart/distribution-bar-chart.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-results/assessment-results.component.html
Fix score card formatting.
Show y axis values as whole numbers.
=> Clm 433 - View Assessment Results

libs/elements/theming/_variables.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-form/assessment-question-form.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts, libs/features/convs-mgr/conversations/question-banks/src/lib/components/add-question-to-assessment/add-question-to-assessment.component.ts, libs/features/convs-mgr/conversations/question-banks/src/lib/components/delete-question-modal/delete-question-modal.component.html, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-header/question-bank-header.component.html, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-header/question-bank-header.component.scss, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.html, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.ts, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-card/question-card.component.html, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-card/question-card.component.ts, libs/model/convs-mgr/conversations/assessments/src/lib/assessment-questions.interface.ts, libs/state/convs-mgr/conversations/assessments/src/lib/services/assessment.service.ts
=> [CLM-34] 🐛  Bug Fixes Question Banks 

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/conversations/question-banks/src/lib/components/delete-question-modal/delete-question-modal.component.scss, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.html, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.scss, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.ts
Add sort questions by date functionality .
Update delete question modal styling.
=> CLM 34 - Question banks

libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.html, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.scss, libs/features/convs-mgr/conversations/question-banks/src/lib/components/question-bank-list/question-bank-list.component.ts, libs/features/convs-mgr/conversations/question-banks/src/lib/utils/sorting-options.enum.ts
Add a select dropdown for date sorting.
=> ✨CLM 34 - Question banks

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/stories/builder/blocks/library/story-module-block/src/lib/components/create-module-modal/create-module-modal.component.html, libs/features/convs-mgr/stories/builder/blocks/library/story-module-block/src/lib/components/create-module-modal/create-module-modal.component.scss
Modules - modal redesign and label text update.
=> 💄 CLM 547 - Modules Brick
