CODE_OF_CONDUCT.md
Add code of conduct doc as required in [open source projects](https://opensource.guide/code-of-conduct/). Got the template from GitHub.
=> :memo: Add code of conduct document

apps/conv-learning-manager/src/app/app.module.ts, libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.html, libs/features/convs-mgr/home/src/lib/components/story-list-item/story-list-item.component.scss
Change three dot menu on bot card to use angular material with a menu for delete and copy
Fixes #102
=> :art: (bot actions menu) add mat icon for delete and edit

libs/elements/theming/common.theme.scss, libs/features/convs-mgr/home/src/lib/pages/home/home.page.scss, libs/features/convs-mgr/stories/home/src/lib/components/story-list-item/story-list-item.component.html, libs/features/convs-mgr/stories/home/src/lib/components/story-list-item/story-list-item.component.scss, libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.html, libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.scss, libs/features/convs-mgr/stories/home/src/lib/pages/stories-dashboard/stories-dashboard.component.html, libs/features/convs-mgr/stories/home/src/lib/pages/stories-dashboard/stories-dashboard.component.scss
The height and width of the components are the same (same goes for the story image). The bot cards also have a "space-between" alignment to ensure they are evenly distributed with a maximum of 4 on each line.
The description only span 3 lines, it was too long and now the if it is the number of characters are limited  and  "...." is added to the end of the last line.
=> :construction: WIP

apps/conv-learning-manager/src/app/app.module.ts, apps/conv-learning-manager/src/index.html, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu-footer/sidemenu-footer.component.scss, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss, libs/elements/layout/page-convl/src/lib/components/convl-sidenav-container/nav-wrapper.component.scss, libs/elements/layout/page-convl/src/lib/convl-page.module.ts, libs/elements/layout/page/src/lib/components/app-navbar-side/navbar-side.component.scss, libs/elements/layout/page/src/lib/components/app-navbar/navbar.component.scss, libs/elements/layout/page/src/lib/components/sidemenu-footer/sidemenu-footer.component.scss, libs/elements/layout/page/src/lib/components/sidemenu/sidemenu.component.scss, libs/elements/layout/page/src/lib/components/sidenav-container/nav-wrapper.component.scss, libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.scss, libs/elements/layout/user-menu/src/lib/user-menu.module.ts, libs/elements/theming/common.theme.scss, libs/features/app/auth/login/src/lib/auth.module.ts, libs/features/convs-mgr/home/src/lib/pages/home/home.page.scss, libs/features/convs-mgr/stories/home/src/lib/components/story-list-item/story-list-item.component.scss, libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.scss, libs/features/convs-mgr/stories/home/src/lib/features-convs-mgr-stories-home.module.ts, libs/features/convs-mgr/stories/home/src/lib/modals/delete-bot-modal/delete-bot-modal.component.scss, package.json
With the new angular material version, Introduced a few changes like:
- moving from @import to @use 
- mat-color was changed to mat.get-color-from-palette method
- defining palletes was changed from mat-pallete to mat.define-palette
- The input on the typography level seems to have been removed as well: https://material.angular.io/guide/typography
=> (WIP)Update Angular Material Theming System

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu-footer/sidemenu-footer.component.scss, libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss, libs/elements/layout/page/src/lib/components/sidemenu-footer/sidemenu-footer.component.scss, libs/elements/layout/page/src/lib/components/sidemenu/sidemenu.component.scss, libs/elements/layout/user-menu/src/lib/components/user-menu/user-menu.component.scss, libs/elements/theming/_theme.scss, libs/elements/theming/_variables.scss, libs/features/convs-mgr/stories/home/src/lib/components/story-list-item/story-list-item.component.scss, libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.scss
- Updated the scss files and replaced mat.get with variables from _variables.scss. 
- Removed redundant imports of _theme.scss from above files.
- Updated _theme.scss to also use variables from _variables.scss
=> 🎨 Update scss files with variables from _variables.scss

libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html
Delete block function was not working. Fixed it by moving it to the span wrapping the icon
=> 🐛 Fix delete block not working

libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.html, libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.scss, libs/features/convs-mgr/stories/home/src/lib/components/story-list/story-list.component.ts
This is more of a fix and enhancement from a closed issue (#72 )
I noticed that when you click on the **create my first bot!** card in the `Active Bots>Dashboard` page, it doesn't pop up the `CreateBotModalComponent` as expected.
To fix this, I reused the `openCreateDialog()` function in CreateBotModalComponent and attached it to the Card through a click event.
This PR fixes and enhances a closed issue #72 
https://user-images.githubusercontent.com/72970552/210243740-8a36420b-61fa-4a9f-b484-75c6b2a23766.mp4
No test required as this is an UI enhancement
=> :wrench:  fix: added modal feature to 'create-my-first-bot' card

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/index.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/open-ended-question-edit/open-ended-question-edit.component.html, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/open-ended-question-edit/open-ended-question-edit.component.scss, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/open-ended-question-edit/open-ended-question-edit.component.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/convs-mgr-edit-block-module.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/fetch-active-block-component.function.ts
Add Open ended Qstns block edit form. depends on #288
=> 🧱 🖊️  Open ended Qstns edit forms

libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.scss
I created a scroll bar on the block list section that is only displayed on hover.
Fixes #306 - https://github.com/italanta/elewa/issues/306
[Elewa Conversational Learning Manager (2).webm](https://user-images.githubusercontent.com/53146890/220586607-9255f552-1ae2-489c-871e-9c0151941d32.webm)
=> feat: creates a scroll bar

libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.scss
Fix block option width being too small by setting it to 90%.
=> 🎨 Fix block option width being too small

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.html, libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.scss, libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/components/option-input-field/option-input-field.component.ts, libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/convs-mgr-block-options.module.ts, libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.html, libs/features/convs-mgr/stories/blocks/library/list-message-block/src/lib/components/list-block/list-block.component.ts, libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.html, libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.ts
This pull request is made in part to handle number of options and character limit on the question and list blocks.
For the list block:
- A maximum of 10 options with a maximum of 24 characters each.
For the question block
- A maximum of 3 options with a maximum of 20 characters each
Fixes #302 
- Type into option input and evaluate input size set to 20 for question block and 24 for list block.
- Created a question block to test possible options and the limit works at 3.
- Created a list block to test possible options and the limit works at 10.
=> 🎨🔢 Set limit to number of characters and possible options on question and list block options

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/components/end-anchor/end-anchor.component.html, libs/features/convs-mgr/stories/blocks/library/anchor-block/src/lib/components/end-anchor/end-anchor.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts
Adding the end block to the block list so that I can easily find it and use it when building conversational flows.
I have put it on the second position so it is easy to spot
Fixes #355 
[Screencast from 27-03-23 11:32:48.webm](https://user-images.githubusercontent.com/109944021/227893261-aa432c3a-5a2d-486f-a83d-01f2cef913a5.webm)
On clicking the end block on the block list, it shows up in the editor frame.
=> 🎨 Move End Block to Block List #355

libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/location-input-block-edit/location-input-block-edit.component.html, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/location-input-block-edit/location-input-block-edit.component.ts, libs/features/convs-mgr/stories/blocks/library/location-input-block/src/lib/location-input-block/location-input-block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/location-input-block-form.model.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/location-validations/location-validations.component.html, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/location-validations/location-validations.component.scss, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/location-validations/location-validations.component.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/variable-input/variable-input.component.html, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/variable-input/variable-input.component.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/convs-mgr-process-inputs.module.ts
Process user responses on the location input block as a variable, select the variable type, add unique validation and add a validation message that will be shown to the user if it doesn't match.
Added Regex validation for this issue.
Fixes #406
=> :floppy_disk: :pushpin:  Save Location Input Block Result As a Variable #406

libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/email-block-edit/email-block-edit.component.html, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/email-block-edit/email-block-edit.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/email-block-form.model.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/email-validations/email-validations.component.html, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/email-validations/email-validations.component.scss, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/email-validations/email-validations.component.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/variable-input/variable-input.component.html, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/convs-mgr-process-inputs.module.ts
Process user responses on the email block as a variable, regex and add a validation message that will be shown to the user if it doesn't match.
Fixes # (issue) -  Fixes #394 Save Email Input Block Result As a Variable
https://user-images.githubusercontent.com/69570282/231961652-54514c24-4124-48f0-b6a4-8eb85f0d9440.mp4
=> 💾 📧 Save Email Input Block Result As a Variable

libs/functions/bot-engine/main/src/index.ts, libs/functions/bot-engine/main/src/lib/handlers/send-outgoing-message.handler.ts, libs/functions/bot-engine/main/src/lib/io/outgoing-message.parser.ts, libs/functions/bot-engine/main/src/lib/model/active-channel.service.ts, libs/functions/bot-engine/main/src/lib/services/data-services/messages.service.ts, libs/functions/bot-engine/main/src/lib/services/variable-injection/mail-merge-variables.service.ts, libs/functions/bot-engine/whatsapp/src/lib/io/outgoing-message-parser/whatsapp-api-outgoing-message-parser.class.ts, libs/functions/bot-engine/whatsapp/src/lib/models/whatsapp-active-channel.model.ts, libs/functions/bot-engine/whatsapp/src/lib/whatsapp-send-message.handler.ts, libs/model/convs-mgr/conversations/messages/src/index.ts, libs/model/convs-mgr/conversations/messages/src/lib/message-params.interface.ts, libs/model/convs-mgr/conversations/messages/src/lib/message-template-config.interface.ts, libs/model/convs-mgr/conversations/messages/src/lib/message.interface.ts, libs/model/convs-mgr/functions/src/lib/whatsapp/whatsapp-template-message.interface.ts
This pull request fixes the issue with sending message templates among some improvements on the same. The time conversation failed and return NaN.
The params passed from the Message object are given a priority over the ones on the template Config in the channel. But if neither is included, the template message is sent without params
=> 🔀 🤖  Fix message templates not working

angular.json, apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/features/convs-mgr/stories/blocks/library/assessment-brick/.eslintrc.json, libs/features/convs-mgr/stories/blocks/library/assessment-brick/README.md, libs/features/convs-mgr/stories/blocks/library/assessment-brick/jest.config.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/index.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.html, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.scss, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/components/assessment-brick/assessment-brick.component.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/convs-mgr-assessment-brick.module.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/lib/providers/decorate-jsplumb.provider.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/src/test-setup.ts, libs/features/convs-mgr/stories/blocks/library/assessment-brick/tsconfig.json, libs/features/convs-mgr/stories/blocks/library/assessment-brick/tsconfig.lib.json, libs/features/convs-mgr/stories/blocks/library/assessment-brick/tsconfig.spec.json, libs/features/convs-mgr/stories/blocks/library/main/src/lib/blocks-library.module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/assessment-brick-form.model.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/icons-and-titles.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/assessment-brick.jsplumb.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.html, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/fetch-active-block-component.function.ts, libs/model/convs-mgr/stories/blocks/main/src/lib/story-block-types.enum.ts, libs/model/convs-mgr/stories/blocks/messaging/src/index.ts, libs/model/convs-mgr/stories/blocks/messaging/src/lib/assessment-brick.interface.ts, tsconfig.base.json
This pull request creates a block for the assessment brick.
Fixes (no issue on this has been created yet)
=> 🧱  Assessment brick

libs/features/convs-mgr/stories/home/src/lib/modals/create-bot-modal/create-bot-modal.component.ts, libs/features/convs-mgr/stories/home/src/lib/services/new-story.service.ts
This pull request seeks to solve issue [#334 ], where I've created a feature to enable a user to seamlessly upload and display on the active bot, a new bot image, solving the bug.
Fixes # (#334 )
[Screencast from 04-20-2023 05:07:17 PM.webm](https://user-images.githubusercontent.com/108331299/233392374-472b6dcd-962e-4950-a75b-25fa7906a6dd.webm)
=> #334 ✨ 🐛  update active bot image

libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/variable-input/variable-input.component.ts
At the moment a block's FormGroup is updated with all the values after submission but our state does not track that, This is because we use a cloned form group to collect the values, and validate whether it's not used before we set it to the blocks form group. The issue is how we set it, we equate our blocksFormGroup to the cloned version which is not watched by our state.  
We Solve the issue but patching the values to our existing BlocksFormGroup instead of equating our FormGroup to our cloned version.
=> :recycle: fix: persist block variables state.

libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/image-input-block-edit/image-input-block-edit.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/image-input-block-form.model.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/variable-input/variable-input.component.ts
As an org, we should be able to save image responses as variables. 
After a user is prompted for an image, the result should be saved as a variable of type string
Fixes #441
[Screencast from 02-05-23 09:47:54.webm](https://user-images.githubusercontent.com/109944021/235599662-1c67bd49-80fb-4a6b-af57-583db9e0c010.webm)
I have the expected behavior as shown in the uploaded screencast.
=> :floppy_disk: Save Image Input Block Result As a Variable #441

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/open-ended-question-edit/open-ended-question-edit.component.html, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/components/open-ended-question-edit/open-ended-question-edit.component.ts, libs/features/convs-mgr/stories/blocks/edit/blocks-edit/src/lib/convs-mgr-edit-block-module.ts, libs/features/convs-mgr/stories/blocks/library/main/src/lib/model/open-ended-question-block-form.model.ts, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/components/open-ended-question-block/open-ended-question-block.component.html, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/components/open-ended-question-block/open-ended-question-block.component.ts, libs/features/convs-mgr/stories/blocks/library/open-ended-question-block/src/lib/convs-mgr-open-ended-question-block.module.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/open-ended-validations/open-ended-validations.component.html, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/open-ended-validations/open-ended-validations.component.scss, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/open-ended-validations/open-ended-validations.component.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/variable-input/variable-input.component.html, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/components/variable-input/variable-input.component.ts, libs/features/convs-mgr/stories/blocks/process-inputs/src/lib/convs-mgr-process-inputs.module.ts
This pull request solves issue #444 that required me to create an edit panel for open ended questions.
=> 💾 📝  Save Open-Ended Question Block Result As a Variable 

libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts, libs/state/convs-mgr/stories/block-connections/src/lib/services/block-connections.service.ts, libs/state/convs-mgr/stories/block-connections/src/lib/stores/story-connections.store.ts
When a block with connection is deleted without being saved, the connections were huddling together in a strange manner instead of being deleted. 
I have updated the delete connection method to filter out connection associated with the block in state instead of looking for those connections in storage 
Fixes #424 
[Screencast from 18-05-23 11:06:06.webm](https://github.com/italanta/elewa/assets/109944021/eaef74fd-63c8-41b2-9597-b0146a42d30c)
Connections are deleted in state and not in storage.
=> :bug: fix deleted blocks connection bug when a story is not saved #424

libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-list/assessment-list.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-results/assessment-results.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/pages/assessment-view/assessment-view.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-metrics.service.ts, libs/features/convs-mgr/conversations/assessments/src/lib/utils/chart.util.ts, libs/model/convs-mgr/conversations/assessments/src/lib/assessment.interface.ts
This PR computes metrics on the assessment view page and also does the following:
-  moves all metrics calculations to a shared service.
-  refactors the edit route functionality on the assessment results page (we now get the mode from queryParams on the assessment view page).
- Generates an empty chart when all values are zero.
=> 🔢 🚚 Assessment View Page Metrics And Code Structure Update

libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.html, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.scss, libs/features/convs-mgr/stories/editor/src/lib/components/blocks-library/blocks-library.component.ts, libs/features/convs-mgr/stories/editor/src/lib/components/grouped-blocks/grouped-blocks.component.html, libs/features/convs-mgr/stories/editor/src/lib/components/grouped-blocks/grouped-blocks.component.scss, libs/features/convs-mgr/stories/editor/src/lib/components/grouped-blocks/grouped-blocks.component.ts, libs/features/convs-mgr/stories/editor/src/lib/components/pipes/block-category-pipe.pipe.ts, libs/features/convs-mgr/stories/editor/src/lib/convl-story-editor.module.ts
Before, when a user searched for a block, the block was filtered but the headings of other blocks were also showing below the relevant result. 
For this fix, I am suggesting that for a filter to fully match, both the heading and block texts have to match, thus returning only the relevant results for both the category and blocks under it.
Fixes #466 
[Screencast from 28-06-23 16:18:58.webm](https://github.com/italanta/elewa/assets/109944021/01ea5ce1-5bf3-4c62-bb4a-bff27070aefb)
)
Only relevant results show on search.
=> :bug: :mag: When I search for an item I should only see relevant results fix #466

apps/conv-lm-backend/src/app/bot/whatsapp-channel/whatsapp-upload-media.function.ts, apps/conv-lm-backend/src/main.ts, libs/functions/bot-engine/main/src/index.ts, libs/functions/bot-engine/main/src/lib/services/bot-engine-play.service.ts, libs/functions/bot-engine/main/src/lib/services/data-services/blocks.service.ts, libs/functions/bot-engine/whatsapp/src/index.ts, libs/functions/bot-engine/whatsapp/src/lib/io/outgoing-message-parser/whatsapp-api-outgoing-message-parser.class.ts, libs/functions/bot-engine/whatsapp/src/lib/whats-app-upload-media.handler.ts, libs/model/convs-mgr/stories/blocks/messaging/src/lib/file-message-block.interface.ts, libs/model/convs-mgr/stories/main/src/lib/story.interface.ts, package.json
This solves the issue of medias lagging on whatsapp by coming after a text that was configured to follow it. Involves uploading the media to whatsapp using a handler and updating the media block with the returned whatsapp media id.
Created whatsapp media handler that:
- Goes through all the media blocks and uploads them to whatsap
- Updates the media blocks with the returned media id from whatsapp
- Whatsapp Outgoing Message Parser prioritizes using the media id if it is available
TODO:
- Enforce Whatsapp limit for Videos: 16MB, on the frontend
- The Uploaded media expires after 30 days. So a cron job is needed to update the media
- The handler can be triggered in publishing the story to whatsapp. Therefore when a story is published, we need a publishedOn field to be updated. So that the …
=> ⚡ 📹  Upload media to whatsapp on publish

libs/features/convs-mgr/stories/editor/src/index.ts, libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.html, libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.scss, libs/features/convs-mgr/stories/editor/src/lib/components/editor-frame/editor-frame.component.ts, libs/features/convs-mgr/stories/editor/src/lib/model/story-editor-frame.model.ts, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.html, libs/features/convs-mgr/stories/editor/src/lib/pages/story-editor/story-editor.page.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/editor-frame-spinner.service.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/story-editor-initialiser.service.ts, libs/state/convs-mgr/story-editor/src/lib/providers/story-editor-state.service.ts
Added a spinner  to the editor page to hide the flickering of blocks while being drawn.
fixes Clm 135 blocks and connections keep refreshing on the story editor
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X ] My code follows the style guidelines of this project
- [ X] My changes generate no new warnings
=> :sparkles: CLM-135:  Blocks and connections keep refreshing on the story editor

libs/elements/theming/_variables.scss, libs/features/convs-mgr/home/src/lib/components/home-courses/home-courses.component.scss, libs/features/convs-mgr/home/src/lib/components/home-courses/home-courses.component.ts, libs/features/convs-mgr/home/src/lib/pages/home/home.page.scss
This Pr creates a clear distinction between the card and home background
Fixes #616
=> :lipstick: create distinction between card and background

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
As a user i want the collapsed side navigation to provide me with tab labels when i hover my cursor over an icon.
#618
* Hardware:
* Toolchain:
* SDK:
=> 🎨 💄 Tooltips On Collapsed Side Navigation #618

libs/features/convs-mgr/conversations/chats/src/lib/components/chat-card/chat-card.component.html, libs/features/convs-mgr/conversations/chats/src/lib/components/chat-card/chat-card.component.ts, libs/features/convs-mgr/conversations/chats/src/lib/providers/avatar.provider.ts
Fixes chats user name initial background should change colour if the learner is different.
CLM-248
=> :art:  CLM-248 chats user name initial background should change colour if the learner is different

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
- CLM-323-Align-wording-and-menu-icons
Fixes #786
=> :recycle: CLM-323-Align-wording-and-menu-icons-#786

libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.html, libs/features/convs-mgr/stories/blocks/library/main/src/lib/components/block/block.component.scss, libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.scss
This pull request introduces a horizontal line within the <mat-card> element. The new implementation is aimed at improving the visual representation of the block structure
Before
Now
=> :lipstick: Add thematic break

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.scss
As a user when hovering over the hamburger menu the cursor is a hand pointer.
Fixes #818
=> :lipstick: Changed cursor to hand pointer when hovering over hamburger in menu

libs/features/app/auth/login/src/lib/components/login/login.component.scss, libs/features/app/auth/login/src/lib/components/register/register.component.scss
Here i added an inbuilt style specific to edge to hide the password eye
=> 🐛 Fixed Double Eyes on Edge password Input field #clm-341

libs/elements/layout/page-convl/src/lib/components/convl-sidemenu/convl-sidemenu.component.html
Disable messaging menu tooltip when menu is expanded
=> 💄 CLM-381 Disable messaging menu tooltip when menu is expanded

libs/features/convs-mgr/conversations/assessments/src/lib/components/create-assessment-flow/create-assessment-page/create-assessment-page.component.html
Removed the settings button on the assessment page since there is no feedback option
=> 💄Removed settings button on the assessment page #CLM-354

libs/features/convs-mgr/stories/blocks/library/block-options/src/lib/providers/jsplumb-decorator.function.ts, libs/features/convs-mgr/stories/blocks/library/question-message-block/src/lib/components/questions-block/questions-block.component.ts, libs/features/convs-mgr/stories/editor/src/lib/providers/save-story.service.ts
This PR fixes CLM-405 and CLM-398.
CLM-405 - Removing all endpoints from an element before adding the endpoint solves the issue of the endpoint not appearing next to the option sometimes when added.
CLM-398 - When getting connections from frame, we used to use `jsplumb.Connection.sourceId` which is inconsistent and does not necesarily refer to the element we are connecting to. This has been changed to `jsplumb.Connection.source.id` which is more consistent because it contains our actual html element
=> 🐛 Fix Option issues

apps/conv-learning-manager/src/assets/i18n/en.json, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-forms/assessment-question-forms.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-question-forms/assessment-question-forms.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/create-assessment-flow/create-assessment-page/create-assessment-page.component.html, libs/features/convs-mgr/conversations/assessments/src/lib/components/create-assessment-flow/create-assessment-page/create-assessment-page.component.scss, libs/features/convs-mgr/conversations/assessments/src/lib/components/create-assessment-flow/create-assessment-page/create-assessment-page.component.ts, libs/features/convs-mgr/conversations/assessments/src/lib/providers/create-empty-assessment-form.provider.ts, libs/features/convs-mgr/conversations/assessments/src/lib/services/assessment-form.service.ts, libs/model/convs-mgr/conversations/assessments/src/lib/assessment.interface.ts
1. Add a section where a content creator can add instructions on how the assessment is to be taken.
2. Add assessment configuration settings, for retakes and number of questions to be displayed in a page.
Fixes  CLM-435, CLM-436
=> ✨ ♻️ Add section to configure assessments instructions, question display format and retakes

libs/features/convs-mgr/conversations/assessments/src/lib/components/assessment-config/assessment-config.component.ts
Fix the on and off toggle for assessment retrials on the assessments configurations settings page
=> :bug: fix retry toggle

libs/features/convs-mgr/stories/home/src/lib/components/bots/bots-list-all-courses/bots-list-all-courses.component.scss
Padding increase between search icon and left edge of search box.
Before:
After:
=> 💄  CLM 453 - Bots - search icon on bots home

libs/features/convs-mgr/modules/src/lib/components/modules-lessons-grid-view/modules-lessons-grid-view.component.scss, libs/features/convs-mgr/stories/home/src/lib/components/modules/bot-modules-grid-view/bot-modules-grid-view.component.scss
Fix module and lesson names overflow in bots
Module:
Lesson:
=> 💄  CLM 456 - Bots - module and lesson name bleeding over tile boundary

libs/elements/theming/_variables.scss, libs/private/features/convs-mgr/settings/users/src/lib/components/users/users.component.html, libs/private/features/convs-mgr/settings/users/src/lib/components/users/users.component.scss, libs/private/features/convs-mgr/settings/users/src/lib/custom-pipes/role.pipe.ts, libs/private/features/convs-mgr/settings/users/src/lib/modals/new-user-dialog/new-user-dialog.component.html, libs/private/features/convs-mgr/settings/users/src/lib/modals/new-user-dialog/new-user-dialog.component.scss, libs/private/features/convs-mgr/settings/users/src/lib/settings-users.module.ts
Fix "Content Developer" typo in all roles dropdown and invite member modal.
Set the members table background to white.
Update hover color from blue to teal -> Role dropdown in the invite member modal.
Fix the dropdown icon placement.
Fix the width of the role input field to match the email width.
Increase the spacing between the role field and the call-to-action buttons.
=> 💬💄Clm 496 - Settings - Members - design changes

libs/features/convs-mgr/conversations/chats/src/lib/components/chat-conversation/chat-conversation.component.html, libs/features/convs-mgr/conversations/chats/src/lib/components/chats-list/chats-list.component.html, libs/features/convs-mgr/conversations/chats/src/lib/components/chats-list/chats-list.component.scss
Remove white background in chat space.
Disable next buttons on reaching the last page of current chats.
=> 🐛💄 CLM 479 - Chats - fix dead space on the bottom of the page

apps/conv-learning-manager/src/assets/i18n/en.json, apps/conv-learning-manager/src/assets/i18n/fr.json, libs/elements/theming/_variables.scss, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-editor/flow-editor.component.html, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-editor/flow-editor.component.scss, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-editor/flow-editor.component.ts, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-library-item/flow-library-item.component.html, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-library-item/flow-library-item.component.scss, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-library/flow-library.component.html, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-library/flow-library.component.scss, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-library/flow-library.component.ts, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-screen-settings/flow-screen-settings.component.html, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-screen-settings/flow-screen-settings.component.ts, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/components/flow-type-text/flow-type-text.component.scss, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/flow-builder.module.ts, libs/features/convs-mgr/stories/builder/flow-builder/app/src/lib/pages/story-editor/flow-builder.page.html, tsconfig.base.json
Display a phone frame that has a default message in the editor when the WhatsApp flow screen is opened.
Default message disappears when an element is dragged into the phone frame.
Dragging an element into the phone frame displays an edit screen, screen settings and a button at the bottom of the phone frame.
A scrollbar appears in the frame incase of many elements that exceed the frame's height.
Update stylings for the phone wrapper.
=> ✨ 💄 Clm 550 - Phone Wrapper
